### ISSUE TITLE
make sure users know how to use batch import

### ISSUE THREAD

**Issue by csyversen** [nulib/images#137]

**Comment by jenyoung** [comment]
Steps:

Move Job folder containing Tifs & XML to images_dropbox\batches

In Images, click on Batch Import, enter Job name, click "Create Image Records"

Go to images.northwestern.edu\sidekiq to monitor imporft

**Comment by davidschober** [comment]
@jenyoung and team, this is done correct?

**Comment by davidschober** [comment]
When there are problems dig into sidekiq. Jobs often will restart themselves, if they can't complete they will end up in dead jobs. Content person needs to investigate, images, etc. Sidekiq will give several errors to point.
