### ISSUE TITLE
mount staging on images-s

### ISSUE THREAD

**Issue by davidschober** [nulib/images#142]
## DONE
staging is mounted on "/staging/fedora3s on images-s to replicate images-p

- [x] test done with local mount
- [ ] firewall rules setup on images-s and fedora3s @Toputnal

**Comment by davidschober** [comment]
per @Toputnal temp fix put in for testing. Jim call IT for firewall rules, etc.

**Comment by Debs4Avalon** [comment]
Temporary fix in yesterday by Jim.  Need firewall rules, etc.

**Comment by Debs4Avalon** [comment]
File system is mounted, @Toputnal  has contacted NUIT.

**Comment by Toputnal** [comment]
NUIT Ticket #418458
