### ISSUE TITLE
puppetize ruby >=2.2

### ISSUE THREAD

**Issue by davidschober** [nulib/images#143]
- [ ] images-s
- [ ] images-p
- [ ] menu-s 
- [ ] menu-p
- [x] decide whether use rbenv or not

**Comment by Toputnal** [comment]
I'm moving this to Review because we need to come together and decide what will work best for everyone.  Maybe when MBK is back next week?

**Comment by davidschober** [comment]
We did come to a decision. For now, we were using rbenv/ passenger

**Comment by Toputnal** [comment]
In that case.  I guess this is closed for the time being.  :-)
