### ISSUE TITLE
puppetize postgres >= 9.4

### ISSUE THREAD

**Issue by davidschober** [nulib/images#144]
- [x] images-s
- [x] images-p

**Comment by Toputnal** [comment]
Verify menu-s is working and then check to see what will be needed to migrate menu-p to pe

**Comment by davidschober** [comment]
Jim to verify menu-s and then move to menu-p. And let team know via slack a window for move.

**Comment by Toputnal** [comment]
postgress 9.4 is managed by puppet on menu-s and menu-p now.
