### ISSUE TITLE
records disappear after being published

### ISSUE THREAD

**Issue by davidschober** [nulib/images#149]
To Recreate:
- import record
- publish
- see that record disappears form menu
- see that record is not visible in images

NOTE: there is a google doc tracking images that are not visible. Link from nicole.

**Comment by davidschober** [comment]
google doc https://docs.google.com/spreadsheets/d/1aXVZUge5Dv2O-BkVN-sHJsoW7s82363qWE0aVanG7pE/edit?usp=sharing

**Comment by jenyoung** [comment]
Nothing is being published from MENU on production consistently.

**Comment by jenyoung** [comment]
Imported Job folder 66666666 into MENU

Edited 1920950.tiff

Save button works

Hit Publish button- no error message given.  Image not removed from MENU and does not appear in Images.

Receive email that my image did not publish.

![2016-08-31_170738](https://cloud.githubusercontent.com/assets/2250501/18148117/739f04e4-6f9d-11e6-983e-7adbcad02b4f.jpg)


I tried to publish 3 different images in that folder, none published.

Previously this bug was inconsistent but now seems consistent.

**Comment by jenyoung** [comment]
This real image from MENU published successfully. https://images.northwestern.edu/multiresimages/inu:dil-f7e5dc3d-95e5-4885-8ff3-9fb532e039c1

**Comment by davidschober** [comment]
The not deleting itself is recorded in another bug, correct?

**Comment by jenyoung** [comment]
Yeah I just realized that

**Comment by jenyoung** [comment]
This spreadsheet, on the "Didn't show up in Images" tab are the records that disappeared upon publish. 70 images
https://docs.google.com/spreadsheets/d/1E_JalcFujq6SIDgvC9PAs-9Dxi3XgfdunI9OrjXeNa0/edit#gid=197352268

**Comment by davidschober** [comment]
We will have to reverify on Production as this is inconsistent.

**Comment by jenyoung** [comment]
between 9-9:30 am 9/15, Erin tried publishing images from Job 11479. 13 were successful and made it into images. 6 of them published, vanishing from MENU (like normal), but did not make into Images. They cannot be found.  Those 6 are:

314656
316657
316658
316659
316660
316661

She also published one from Job 11502 at about 11:30 that also did not make it into Images, 314852.

**Comment by davidschober** [comment]
Jen, can you add any  bit of metadata that we might be able to search on?

**Comment by jenyoung** [comment]
I looking for some metadata for you -- doing that, I see that all of these 7 of these images are now showing in Images. Six of them took ~6 hours to appear. That seems excessive. 

I'm having Erin going through the spreadsheet with all of the other "missing" images to verify that they never appeared later in Images.  

How should we move forward?

**Comment by jenyoung** [comment]
Links to the records:
https://images.northwestern.edu/multiresimages/inu:dil-fed94b63-3a76-4c2b-a456-9a48604fbcda
https://images.northwestern.edu/multiresimages/inu:dil-5c698016-e611-43ea-8c58-dcfea18b3c73
https://images.northwestern.edu/multiresimages/inu:dil-ace22974-ae67-48cf-a739-9be3a474f12e
https://images.northwestern.edu/multiresimages/inu:dil-b1e122bc-b84a-42f3-96c7-b36f6c9f9d6d
https://images.northwestern.edu/multiresimages/inu:dil-a0b763b4-b040-4aea-b4be-b53bbce75226
https://images.northwestern.edu/multiresimages/inu:dil-f6e0eef0-9ff6-4186-a11c-1db2f4638583
https://images.northwestern.edu/multiresimages/inu:dil-580dcafd-3c68-4861-9ca9-3c4b1f3474ed

**Comment by jenyoung** [comment]
After talking to David, we're going to do some more testing and watching about this issue. Nicole is also hitting Fedora pretty hard so it might just need time to catch up. We're going to keep this on hold and add more information as needed. Thanks!

**Comment by davidschober** [comment]
jen and erin are moving through the spreadsheet, verifying and deleting as a qc measure. They will close when this is complete.

**Comment by davidschober** [comment]
@jenyoung this leveled out right? We can close.

**Comment by jenyoung** [comment]
@davidschober it's not happening for new jobs, but is still happening for old jobs.

**Comment by jenyoung** [comment]
@egilchrist - is this still an issue or have we gotten through most of them?

**Comment by jenyoung** [comment]
per @egilchrist these are only happening with 6 images from La Caricature. Waiting for images from production staff to reingest. Closing since not currently happening.
