### ISSUE TITLE
retest batch

### ISSUE THREAD

**Issue by davidschober** [nulib/images#165]
## DONE

After isilon mount is working verify that batch moves items properly

- [x] make sure configs are right for staging and production
- [x] make sure image mover module uses the right configs and 
- [x] points to the right destination 
- [x] documentation of issues

**Comment by davidschober** [comment]
error while trying to contact libfedora3 with a delete. problem might be that it's read only mode. Check with @d-venckus

**Comment by davidschober** [comment]
#220

**Comment by davidschober** [comment]
@jenyoung can you close this if you're done?

**Comment by davidschober** [comment]
@jenyoung. We are going to need some thorough testing on this feature. Can you do some negative tests. 

We need to test a good set and a bad set. 
- [ ] VRA bad
- [ ] dupes. run the same batch twice. Dupes that are within batch. 
- [ ] batch of one
- [ ] kick off more than one batch at one time
- [ ] determine if metadata is correct. 
- [ ] pick a sample image and make sure all metadata is imported properly

**Comment by davidschober** [comment]
@jenyoung is this done? Can you move?

**Comment by jenyoung** [comment]
@davidschober no - you wanted me to test all the new items you added. I've written scripts and created files for it. Now need the files to be moved to the staging dropbox since I can't.
