### ISSUE TITLE
Public Collections: Add thumbnail images to search results pages

### ISSUE THREAD

**Issue by Debs4Avalon** [nulib/images#171]
## DONE
- [x] Results of searching for an image to add to a collection are displayed with a corresponding thumbnail
- [x] thumbnails use riiif

**Comment by bmquinn** [comment]
@davidschober @Debs4Avalon Is this issue referring to the new public collections functionality?

**Comment by davidschober** [comment]
I believe so. I copied it over from the groomed Jira.
