### ISSUE TITLE
Monitoring MENU

### ISSUE THREAD

**Issue by davidschober** [nulib/images#182]
## DONE

Menu is being monitored by our monitoring software.
- [ ] DB is being monitored for up
- [ ] website up is being monitored
- [ ] fedora is being monitored
- [ ] SOLR is being monitored.

**Comment by davidschober** [comment]
It's ok if initially this just checks for a 200.

**Comment by Toputnal** [comment]
note: see "about" page for Avalon.

**Comment by davidschober** [comment]
@bmquinn @kdid @csyversen can we steal Avalon's page so that Jim can hit the page and grep it for errors? ^^^^^

**Comment by davidschober** [comment]
@Toputnal I talked with the team the avalon "about" page is a standard hydra thing. It's already there and available in staging for images. But it's currently only running in staging. We would like to have only solrwinds (or nagios) have access to it in production, can you send over the IP address?

For menu, a simple 200 returning from the box should be OK.

**Comment by csyversen** [comment]
i kind of think we should just close this issue. Lets just focus our attention on future things instead. Sound good?

**Comment by csyversen** [comment]
ok, closing! we might address this later if we need to
