### ISSUE TITLE
Email being sent repeatedly to repodev box

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#189]
Write this as a bug in github, attach this.

David 

On Aug 4, 2016, at 2:19 PM, Nicole Gabrielle Finzer <n-finzer@northwestern.edu> wrote:

Hi,

I do not understand what is doing but it would seem a batch of images is sending a message to our R&DC email account.

Shall I share this with the devs?

Thanks, 
N.

From: NUL-Repository <repository@northwestern.edu>
Date: Thursday, August 4, 2016 at 1:57 PM
To: nicole finzer <n-finzer@northwestern.edu>
Subject: FW: Undeliverable: The status of your batch of Images records

Something weird going on…this email ended up in the repo email box like 5x in the past hour

From: Microsoft Outlook <MicrosoftExchange329e71ec88ae4615bbc36ab6ce41109e@e.northwestern.edu>
Date: Thursday, August 4, 2016 at 1:16 PM
To: "YOUREMAILHERE@northwestern.edu" <YOUREMAILHERE@northwestern.edu>
Subject: Undeliverable: The status of your batch of Images records

Delivery has failed to these recipients or groups:

YOUREMAILHERE@northwestern.edu
The e-mail address you entered couldn't be found. Please check the recipient's e-mail address and try to resend the message. If the problem continues, please contact the NUIT Support Center at 847-491-HELP (4357) or www.it.northwestern.edu/supportcenter/.

Diagnostic information for administrators:

Generating server: evcspmbx05.ads.northwestern.edu
YOUREMAILHERE@northwestern.edu
Remote Server returned '550 5.1.1 RESOLVER.ADR.RecipNotFound; not found'
Original message headers:

Received: from EVCSPCAS03.ads.northwestern.edu (165.124.43.167) by
 evcspmbx05.ads.northwestern.edu (165.124.43.177) with Microsoft SMTP Server
 (TLS) id 15.0.1076.9; Thu, 4 Aug 2016 13:16:20 -0500
Received: from evcspprf10.ads.northwestern.edu (165.124.82.241) by
 EVCSPCAS03.ads.northwestern.edu (165.124.43.167) with Microsoft SMTP Server
 (TLS) id 15.0.1076.9 via Frontend Transport; Thu, 4 Aug 2016 13:16:20 -0500
Received: from pps.filterd (evcspprf10.ads.northwestern.edu [127.0.0.1])
	by evcspprf10.ads.northwestern.edu (8.15.0.59/8.15.0.59) with SMTP id u74ICcwX005914
	for <YOUREMAILHERE@northwestern.edu>; Thu, 4 Aug 2016 13:16:20 -0500
Received: from dhcp-10-105-151-31.wireless.northwestern.private (dhcp-10-105-151-31.wireless.northwestern.private [10.105.151.31])
	by evcspprf10.ads.northwestern.edu with ESMTP id 24m9p28gmq-1;
	Thu, 04 Aug 2016 13:16:20 -0500
Received: by bquinn2013-mac.local (Postfix, from userid 500000813)
	id 60731473E7F2; Wed,  3 Aug 2016 15:36:39 -0500 (CDT)
Date: Wed, 3 Aug 2016 15:36:39 -0500
From: <repository@northwestern.edu>
To: <YOUREMAILHERE@northwestern.edu>, <jennifer.lindner@northwestern.edu>
Message-ID: <57a255d7179ce_917a3fea170eba8c99350@bquinn2013-mac.local.mail>
Subject: The status of your batch of Images records
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10432:,, definitions=2016-08-04_10:,,
 signatures=0
X-Proofpoint-Spam-Details: rule=inbound_notspam policy=inbound score=1 spamscore=1 suspectscore=10
 malwarescore=0 phishscore=0 adultscore=0 bulkscore=0 classifier=spam
 adjust=0 reason=mlx scancount=1 engine=8.0.1-1604210000
 definitions=main-1608040195
Return-Path: repository@northwestern.edu
<Mail Attachment.eml>

**Comment by bmquinn** [comment]
We shouldn't emails from dev/test but apparently that's happening (see the "Received: by bquinn2013-mac.local" above). Karen is making an issue for this now.

**Comment by bmquinn** [comment]
Chris and I discussed this issue and we feel like since it's not causing any serious problems we're going to leave it for now. Will come back to this in a few weeks if time allows.
