### ISSUE TITLE
Remove actual email sending during local development

### ISSUE THREAD

**Issue by kdid** [nulib/images#190]
In several places, operations send actual emails to others while testing locally. Need to identify where and change. Both menu and images

Also make clear in emails which environment they come from (prod, staging, menu, images)

Discuss removing admin_email from batch emails altogether.

Currently sending two emails in the case of failure, there should be only one.

**Comment by bmquinn** [comment]
Chris and I discussed this issue and we feel like since it's not causing any serious problems we're going to leave it for now. Will come back to this in a few weeks if time allows.
