### ISSUE TITLE
Dev Ops ticket: Monitor delayed jobs

### ISSUE THREAD

**Issue by Debs4Avalon** [nulib/images#196]
## DONE

-  [x] delayed jobs restarts automatically
-  [ ] plan for monitoring MENU
- [ ] does it come up on Vagrant box

**Comment by Toputnal** [comment]
I reworked the delayed_job script in /etc/init.d/ so that the built-in rhel 'service' command now works with delayed_job.  Now, puppet also monitors service delayed_job status and restarts delayed_job properly if it is ever not running.  This is currently working on menu-s.  --JRB

**Comment by Toputnal** [comment]
This has also been done on menu-p  :-)
