### ISSUE TITLE
inconsistent test results due to inconsistent presence of images 

### ISSUE THREAD

**Issue by jenlindner** [nulib/images#20]
The same image causes the tests to fail for two of three developers locally, same code. Something must be slightly off.

**Comment by jenlindner** [comment]
Chris and I talked, we could just add some images we know are viable for everybody to the test group we create.

**Comment by csyversen** [comment]
oh so we did this in our dev branches (the updated fixtures), so do you think we can close this?

**Comment by csyversen** [comment]
i'm doing it!
