### ISSUE TITLE
Test editing existing record on staging

### ISSUE THREAD

**Issue by davidschober** [nulib/images#206]
- [x] grab pid from images-s
- [x] enter pid into form  on menu-s
- [x] verify that thumbnail shows up/ big image/ vra editor contains xml
- [x] write bugs if necessary.

**Comment by jenyoung** [comment]
Big image does not display on editing an existing record.

**Comment by davidschober** [comment]
@jenyoung can get an update on this?

**Comment by jenyoung** [comment]
@davidschober there's a bug waiting to be fixed.

**Comment by davidschober** [comment]
I believe that was moved to staging. Can the team verify.

**Comment by jenyoung** [comment]
Still not displaying on staging.

**Comment by jenyoung** [comment]
this is fixed on production.
