### ISSUE TITLE
Inconsistent test results from timing variations from computer to computer

### ISSUE THREAD

**Issue by jenlindner** [nulib/images#21]
Might be fixed by upgrading Capybara, in many cases in the tests, but some of the tests require going to a new page, which Capybara doesn't seem to address. Needs looking into.

**Comment by csyversen** [comment]
i say we just get rid of images on the site altogether

**Comment by jenlindner** [comment]
yeah, why don't we just describe them?

**Comment by csyversen** [comment]
oh this works on the new branch!!
