### ISSUE TITLE
menu isn't responding to duplicate accession numbers correctly

### ISSUE THREAD

**Issue by csyversen** [nulib/images#214]
### Descriptive summary

Menu isn't displaying any error message when trying to publish a duplicate record. 

Images is correctly identifying the record as a dupe, but menu isn't correctly handling the return.

### Expected behavior

Menu should communicate to the user via the flash that this record has a duplicate accession number

### Actual behavior

Menu acts like it was a successful publish

**Comment by csyversen** [comment]
i was expecting the old behavior, now apparently menu uses emails as it's notifications.

**Comment by davidschober** [comment]
Should we do both? Email makes sense with batch upload, but it seems odd if you're only importing a few to rely on email. Maybe we can put this low.

**Comment by davidschober** [comment]
Removing  a flash message  was changed in February. In order to deal with this in an immediate way, we will need to do a significant refactor.
