### ISSUE TITLE
pointing to wrong vra location on production

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#215]
### Descriptive summary

Erin came across a record she was editing from Images that doesn't display the metadata
https://images.northwestern.edu/multiresimages/inu:dil-7a19b3f3-f476-41ae-8da7-af2625ecbbd2

Looking at the XML metadata that does exist in MENU, I noticed 2 things. Pointing to wrong XSD
but also the vra:vra tag is missing a end bracket. I fix it and then it throws errors.

These were records that have been recently published.

### Expected behavior

It should be pointing to https://www.loc.gov/standards/vracore/vra.xsd

### Actual behavior

This is on production. I know I came across a similar one earlier. I’m looking at the xml and the vra namespace is wrong. Instead of xmlns:vra=http://www.vraweb.org/vracore4.htm

![2016-08-18_115257](https://cloud.githubusercontent.com/assets/2250501/17782774/c2d33ca0-653a-11e6-8e97-e4b70557ac0a.jpg)
![2016-08-18_115449](https://cloud.githubusercontent.com/assets/2250501/17782773/c2d209e8-653a-11e6-8e86-d086daf43ac5.jpg)

**Comment by bmquinn** [comment]
Met with @jenyoung to discuss the issue, and we're all good here. A new issue #216 was written to address the lack of VRA showing up for the image in the Images application.
