### ISSUE TITLE
Cleanup missing VRA works

### ISSUE THREAD

**Issue by csyversen** [nulib/images#216]
### Descriptive summary

The occasional record isn't getting a new VRA work associated for some reason. The VRA Image record exists though, so it's not urgent, but we need to clean up our data at some point. It's not showing image metadata on Images now though

Do a multiresimage.find where related_ids is empty string, and then create work records for those records based off of the existing vra:image record. 

### Expected behavior

When viewing a record on Images, it should display metadata for the image

### Actual behavior

It's not showing up

**Comment by davidschober** [comment]
@csyversen this is a non-issue now correct?

**Comment by csyversen** [comment]
Yep! Closing
