### ISSUE TITLE
Handle duplicate accession numbers in batch validation

### ISSUE THREAD

**Issue by bmquinn** [nulib/images#217]
### Descriptive summary

We should be checking for duplicate records via accession number in batch jobs, so that we prevent race condition duplicates getting saved into Images.
### Expected behavior

The validator will let the user know if they have duplicate accession numbers within their batch records.

**Comment by davidschober** [comment]
This is an edge case.

**Comment by davidschober** [comment]
@csyversen @kdid we can close this correct with a "known issue" This was an edge case as I remember. Batch checks generally for duped accessions.

**Comment by kdid** [comment]
@davidschober - Images checks if the accession number exists in images but not within the batch, so the workaround is to make sure there are no duplicates within the batch.

**Comment by davidschober** [comment]
I think I meant to close this a while ago. Closing now. Please let me know if we need to reopen.
