### ISSUE TITLE
Test restarting server with jobs running

### ISSUE THREAD

**Issue by Debs4Avalon** [nulib/images#224]
DONE means:
When a current job (i.e. a batch upload) is in the sidekiq queue being processed and the services (redis and sidekiq) are restarted upon server reboot, the job is sucessfully saved and then continues to process where it left off..

Note that you can view the sidekiq queue here (staging):
http://images-s.library.northwestern.edu/sidekiq/

**Comment by kdid** [comment]
closing. this seems to be working.
