### ISSUE TITLE
End User Testing for Batch

### ISSUE THREAD

**Issue by Debs4Avalon** [nulib/images#226]
## DONE

- [x] New script written for batch ingest
- [ ] Ok'd by PO & Devs

**Comment by jenyoung** [comment]
Script written and added to Images Testing https://docs.google.com/spreadsheets/d/1-0Wabci6vxZgovkUiL8IxvufYAtnPznoE57Hl-sXXyo/edit#gid=1737678008

**Comment by jenyoung** [comment]
Script here for evaluation https://docs.google.com/spreadsheets/d/1sLE_tzRCM-OgogJu9gciNJWDUKb5CTrbV2qyJ1KX0VA/edit#gid=0

**Comment by csyversen** [comment]
We can close this now, the updated/corrected batch stuff is in production now
