### ISSUE TITLE
Image and record aren't being removed from MENU upon publishing to Images

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#231]
### Expected behavior

The Image and metadata should be removed from MENU once published. This is happening on staging and very importantly production.

### Actual behavior

After publishing, the record stays in MENU.  Also, got email saying my publishing had failed - but the image did show in Images. Despite the email, it did actually get published.

![2016-08-24_110342](https://cloud.githubusercontent.com/assets/2250501/17938173/7a1a8608-69ea-11e6-8afb-7843b8dd90d0.jpg)

This record was published to images-s but is still available via menu-s

![2016-08-30_160431](https://cloud.githubusercontent.com/assets/2250501/18106999/abf77736-6ecb-11e6-8e59-b1b767a1a6a2.jpg)
 

### Steps to reproduce the behavior

1. Publish a record
2. Refresh MENU folder where Image resided - see that it didn't get removed.

**Comment by davidschober** [comment]
@csyversen can you take a look at this bug

**Comment by csyversen** [comment]
sure, once we're done deploying i'll try to duplicate it!

**Comment by jenyoung** [comment]
In this spreadsheet, the "Still in Menu" tab lists all the ones that were published to Images, but not removed from Menu, 602 images.

https://docs.google.com/spreadsheets/d/1E_JalcFujq6SIDgvC9PAs-9Dxi3XgfdunI9OrjXeNa0/edit#gid=0

**Comment by jenyoung** [comment]
#265 to figure out how to clean up after bug fix
