### ISSUE TITLE
Deleted images still available for editing via MENU

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#232]
### Expected behavior

Record and Image should be completely deleted from both Images and MENU.

I was able to successfully completely delete an already-published image from both Images/MENU production.
However, I wasn't able to fully test since publishing to Images is unavailable currently on production. I don't know if it is related to the other bug listed below. 

### Actual behavior

On staging, Record and Image are deleted from Images, but still available via MENU. 

### Steps to reproduce the behavior

1. Copy a pid of an Image that you want to delete from Images
2. Delete record in Images
3. Enter pid into search box in MENU
4. Record and Image are available for editing.

### Related work

I think this is related to this bug:

https://github.com/nulib/images/issues/231

**Comment by kdid** [comment]
Jen, 
We are not able to reproduce this issue. I followed the steps to reproduce and got an error in menu when I searched for the image.
Could you possibly be experiencing an issue with caching?
Can you send an example pid that you've deleted from images-s that is producing an error in menu-s and we can see if we can reproduce it that way?
Karen

**Comment by jenyoung** [comment]
@kdid i can't either. i will blame a ghost in the machine and close. thanks!
