### ISSUE TITLE
Message for Landing Page - ASAP

### ISSUE THREAD

**Issue by Debs4Avalon** [nulib/images#234]
## DONE 

 - [x] Message on Images Landing Page: "Hello, Images will be unavailable between 10:00AM - 5:00PM on Thursday, August 25th.  If you require immediate assistance during that time please contact Nicole Finzer at n-finzer@northwestern.edu."
- [x] Notify NF when up

**Comment by bmquinn** [comment]
Message is up, and Nicole contacted.
