### ISSUE TITLE
verify that thumbnail shows up/ big image/ vra editor contains xml

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#235]
### Descriptive summary

On staging, Big image does not display on editing an existing record. Works on production. Broken on staging. Thumbnail works fine on both staging and production.

from 206 - verify that thumbnail shows up/ big image/ vra editor contains xml

### Expected behavior
Image should display.

### Actual behavior
It does not.
![2016-08-24_152612](https://cloud.githubusercontent.com/assets/2250501/17946758/51f859f0-6a0f-11e6-840e-da0b99388ff0.jpg)

### Related work
https://github.com/nulib/images/issues/206

**Comment by jenyoung** [comment]
this works for new images, not editing an already published record.

**Comment by csyversen** [comment]
menu pr #114 fixes this issue. it needs to be merged and deployed

**Comment by jenyoung** [comment]
fixed on production

**Comment by davidschober** [comment]
Great. Closing this.
