### ISSUE TITLE
puppetize production

### ISSUE THREAD

**Issue by davidschober** [nulib/images#238]
- [x] move to new puppet server
- [x] verify puppetize rules in place
- [x] verify that sidekiq isn't full of old jobs
- [x] migrate changes from staging to production
- [x] redis works
- [x] sidekiq works
- [x] firewall rules

## break in case of emergency
- [ ] call nuit and revert to snapshot

**Comment by Toputnal** [comment]
Move to new puppet server will hopefully happen later today, but the node is currently running the code *almost* all of the code it will be running on pe once the firewall issue is resolved.  Redis and Sidekiq are being monitored by puppet, but a reboot should be done to ensure that they come back up.

**Comment by Toputnal** [comment]
Rebooted and ensured that NFS mounts, redis, and sidekiq started automatically thanks to the new puppet code.

**Comment by Toputnal** [comment]
I have a ticket open with NUIT regarding the firewall issue.  They will call me at some point, today, one hopes.

**Comment by Toputnal** [comment]
As we don't have ANY boxes that have managed firewall rules via puppet in Production, we'll need to table this for later when we implement iptables for prod puppet.
