### ISSUE TITLE
Fix (end user) staging dropbox access for images-s/menu-s

### ISSUE THREAD

**Issue by davidschober** [nulib/images#241]
Currently samba doesn't seem to be working for images/menu dropbox on staging. Jen Young and other users are unable to access dropbox on staging to add and remove files.

They need a way to add and remove files in order to use the menu and images application. 

## DONE

- [ ] Jen Young (and other users) are able to access dropbox (staging) to add and remove files. 
- [ ] Access works the same way on staging as it does in production

**Comment by davidschober** [comment]
This is a bigger issue. Something is odd with samba access.

**Comment by Toputnal** [comment]
There are differences in the way different versions of Windows interact with different versions of Samba.  I will migrate the Samba functionality OFF of menu-s/images-s and ON to librepofiles1s (aka 'po') such that the Samba access works in the same fashion as production (where users drop off files on librepofiles1p (aka 'lala').  Keeping the number of Samba servers to a minimum allows for tweaking Samba settings on fewer servers.  To wit, librepfiles1s (aka 'po') and librepofiles1p (aka 'lala')  currently have the best known compatibility settings for Samba/Windows already in place.

**Comment by Toputnal** [comment]
Opened NUIT ticket 432073 to address this issue.

**Comment by davidschober** [comment]
@jenyoung can you validate and close?

**Comment by Toputnal** [comment]
The Staging  Samba has moved to po.library to match production.  So, users will go to po.library for the Dropbox just as, users go to lala.library to get to the Dropbox for production Images.

**Comment by jenyoung** [comment]
it works!
