### ISSUE TITLE
Don't start and stop sidekiq on reboot anymore (for both staging and prod)

### ISSUE THREAD

**Issue by csyversen** [nulib/images#245]
### Descriptive summary

We learned that rails starts a version of sidekiq when the rails app starts, so puppet doesn't need to start sidekiq on reboot anymore. (When doing a ps -aef | grep sidekiq, we saw that two versions were running, one with the `-bash -c cd /var/www/dil_hydra/current/ && RAILS_ENV=staging bundle exec sidekiq start &` command and another one that corresponded to the time of a new rails deploy)

We still need the process monitored though and the devs should be notified if it goes down so we can restart it

**Comment by Toputnal** [comment]
I have removed sidekiq from management by puppet on both images-s and images-p.  However, we will need some alternate way to monitor if sidekiq is running due to this change.    Coming up with this alternate way to monitor sidekiq will require input from our development team and devops.

**Comment by Toputnal** [comment]
I also stopped the services by hand on both servers, so they ought to both be rebooted soon for this to be a true test.

**Comment by kdid** [comment]
After discussion with Jim, we are closing and opening an updated, accurate issue.
