### ISSUE TITLE
Image quality tests failing for wrong reason during batch ingest on staging

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#251]
### Descriptive summary

Attempted ingest of 20 different images and their corresponding xml files. All files in the image_tests folder in the staging dropbox.

### Expected behavior

All 20 images should Fail. 18 of them should fail because they are not a tif and 2 of them should fail because they are 48-bit tifs.

### Actual behavior

The 18 images that are not tifs all give "Missing Corresponding XML or TIFF" as the error message. The XML files are in the same folder. They are failing for the wrong reason.

The 2 bad tifs are not failing and give no error message. 

![2016-08-29_175634](https://cloud.githubusercontent.com/assets/2250501/18070234/282279ba-6e12-11e6-89d8-2db81bea48a0.jpg)

**Comment by csyversen** [comment]
We don't do any inspection of the TIFFs themselves before they are submitted to a batch. As long as the extension is .tif or .tiff that's ok with the pre-job tests. 

The invalid tiffs might fail once they get enqueued and sidekiq runs the job to transform them, but that's a later point in this process

**Comment by csyversen** [comment]
(if you want there to be pre-job validation of the tiff files, you can submit a new issue with a request for this feature!)
