### ISSUE TITLE
metadata_tests not completely failing

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#252]
### Descriptive summary

There are 7 metadata tests in the metadata_tests folder. This is on staging.

### Expected behavior

One metadata file should pass and the other 6 should fail.

### Actual behavior

The good metadata passes (as it should). Only 2 out of the 6 fail and display an error message.

missing_accession should fail as it is missing an accession number
missing_agent should fail as it is missing the required agent element
missing_date should fail as it is missing the required date element
missing_title should fail as it is missing the required title element

![2016-08-29_181016](https://cloud.githubusercontent.com/assets/2250501/18070515/eda668b2-6e13-11e6-8c1b-ac7d7530a893.jpg)

**Comment by csyversen** [comment]
Those four failing tests aren't part of the VRA spec itself, I think that's a convention that we do here at NUL, right? 

The images app currently validates against the VRA-strict.xsd spec itself, but nothing additionally. We could add in extra functionality, but that's an extra feature that we'd have to implement. 

I'm going to close this bug and add a new feature issue that we can prioritize
