### ISSUE TITLE
batch import is either super slow or isn't working

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#253]
### Descriptive summary

I've uploaded two different batches via batch import on staging. I obviously didn't expect them to completely finish before I left, but I expected some records to be imported. The two batches I are imported "single_test_batch" and "large_test_batch".  It's been almost 90 minutes and not one record has been imported. Looking at https://images-s.library.northwestern.edu/sidekiq/ - there are 1640 records in the "enqueued" section. 
 
![2016-08-29_183454](https://cloud.githubusercontent.com/assets/2250501/18070960/5b82d4b2-6e17-11e6-86e7-a0245fa39e56.jpg)

### Expected behavior

Batch import should have imported a few records at least in about 90 minutes.

### Actual behavior

None have yet shown up on images-s.

**Comment by davidschober** [comment]
sidekiq was not running.

- [ ] restart sidekiq

**Comment by csyversen** [comment]
yep, sidekiq immediately shut itself down for some reason after it started to process jobs. We just started it up again and records immediately started being published to images

**Comment by csyversen** [comment]
Once we get sidekiq managed by puppet this shouldn't be an issue. i'm going to close this bug for now, we can open another one if this problem pops up again
