### ISSUE TITLE
Implement additional VRA metadata checking in Images

### ISSUE THREAD

**Issue by csyversen** [nulib/images#256]
### Descriptive summary

Menu currently implements a couple of custom validation checks for VRA, like checking for the existence of the AgentName, EarliestDate, and Title. We should implement these in Images for batch imports
### Related work

This feature came out of this bug report: #252

**Comment by davidschober** [comment]
@csyversen how critical was /is this? We're putting together a punch list

**Comment by csyversen** [comment]
@davidschober i think the metadata team can work around it, but @jenyoung or nicole (not sure of her github name) is probably the best person to ask

**Comment by davidschober** [comment]
I think you kicked this off right? @csyversen I think e can close this, unless you think it's critical.

**Comment by csyversen** [comment]
i didn't, no. This issue was put on hold for a while

(i'm just trying to keep up to date with all my github issues and so i'm going through any that i'm assigned to or mentioned in)

**Comment by jenyoung** [comment]
i think this can be dropped for now. should be part of next gen validation.

**Comment by davidschober** [comment]
Sounds good. Closing.
