### ISSUE TITLE
editing an existing record on staging not reindexing properly?

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#258]
### Descriptive summary

 Editing via MENU a record. This is on staging. I edited both a record that I added via MENU and one that I added via batch import. Behavior is the same

### Expected behavior

Facets after editing a record should reindex properly - removing old data and only adding one instance of the new data.

### Actual behavior

Edited this record in MENU http://images-s.library.northwestern.edu/multiresimages/inu:dil-8cfe1028-1e0c-4e06-8e03-791a636b1c1a

change: Creator, technique, title, and cultural context. 

Facets are duplicative and not removing the old information upon publishing. 

![2016-08-30_154959](https://cloud.githubusercontent.com/assets/2250501/18106457/6d9d1d80-6ec9-11e6-9994-75ab9464f4c0.jpg)

Another test http://images-s.library.northwestern.edu/multiresimages/inu:dil-bbc22354-462b-465e-8064-536158d4297c
![2016-08-30_155918](https://cloud.githubusercontent.com/assets/2250501/18106823/e1eae5d6-6eca-11e6-8143-58fa04567708.jpg)

**Comment by jenyoung** [comment]
registering on an edited record still on production. I had just added the cultural context to an already published record


![2016-08-31_164601](https://cloud.githubusercontent.com/assets/2250501/18147515/82dcc386-6f9a-11e6-8c87-49223fda01b2.jpg)

**Comment by davidschober** [comment]
Manual query into the console should tell us what the difference between these are.
