### ISSUE TITLE
list of records on production with only metadata

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#263]
### Descriptive summary

Records on "Metadata no image" tab - need to discover why the images disappeared and how to retrieve them. 7 in all. 

https://docs.google.com/spreadsheets/d/1E_JalcFujq6SIDgvC9PAs-9Dxi3XgfdunI9OrjXeNa0/edit#gid=758543320
### Expected behavior

Image should be displaying.
### Actual behavior

No image.
### Steps to reproduce the behavior

Sporadically happening not consistent.

**Comment by Nic4Images** [comment]
These seems to be gone.

**Comment by Nic4Images** [comment]
Correction this is not resolved. Sorry!

**Comment by Nic4Images** [comment]
We need to have Tom re drop these in images_dropbox and then try to ingest them again.

**Comment by davidschober** [comment]
Still on production to get us the originals per @jenyoung

**Comment by jenyoung** [comment]
Six records are still not displaying an image in Images even though it was successfully published in Images. Bringing up the published in record in MENU just shows a broken Default.  These might be really huge Tifs but nothing displays even after an hour of letting try to load.

- http://images.northwestern.edu/multiresimages/inu:dil-ba941c61-70ff-4cc0-94dd-52cc56c9fa8e
- http://images.northwestern.edu/multiresimages/inu:dil-125c5368-f3a4-4cfd-8710-62c4ec37640c
- http://images.northwestern.edu/multiresimages/inu:dil-22c9809d-b76d-4976-9a9a-1185ef0ac8de
- http://images.northwestern.edu/multiresimages/inu:dil-80016f91-3f39-4140-8469-ac5ba71f8c25
- http://images.northwestern.edu/multiresimages/inu:dil-a7a9f701-3c99-4b4f-a867-0b9df264a4c2
- http://images.northwestern.edu/multiresimages/inu:dil-3e1fd840-18b7-4c33-9f8f-cee5694b622d

**Comment by jenyoung** [comment]
still waiting on rescans from production staff

**Comment by jenyoung** [comment]
we should have the rescans by Friday, March 10.

**Comment by jenyoung** [comment]
Images and metadata are there. Closing!
