### ISSUE TITLE
list of images with no metadata on production

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#264]
### Descriptive summary

Records on "Image no metadata" tab - need to discover why the metadata disappeared and how to retrieve them. 2 in all. 

https://docs.google.com/spreadsheets/d/1E_JalcFujq6SIDgvC9PAs-9Dxi3XgfdunI9OrjXeNa0/edit#gid=758543320
### Expected behavior

Metadata should be displaying.
### Actual behavior

No metadata
### Steps to reproduce the behavior

Sporadically happening not consistent.

**Comment by Nic4Images** [comment]
Lets start using "metadata is not visible on front end" in place of disappeared, cool?

**Comment by Nic4Images** [comment]
Ask Tom to drop these on images_dropbox again. Lets try re-ingesting them.

**Comment by jenyoung** [comment]
all fixed and ingested into Image successfully.
