### ISSUE TITLE
Check and remove already published to Images record from MENU.

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#265]
### Descriptive summary

Develop plan for removing already published to Images record from MENU.
Have a list of filenames and pids-"Still in MENU" tab

https://docs.google.com/spreadsheets/d/1E_JalcFujq6SIDgvC9PAs-9Dxi3XgfdunI9OrjXeNa0/edit#gid=0
### Related work

bug fix #231

**Comment by jenyoung** [comment]
Erin is working on it.

**Comment by davidschober** [comment]
renamed to reflect work.

**Comment by jenyoung** [comment]
all have been dealt with.
