### ISSUE TITLE
Manage sidekiq pro environment variable in staging and production via puppet

### ISSUE THREAD

**Issue by csyversen** [nulib/images#278]
### Descriptive summary

Sidekiq pro requires a bundle config value (since we're licensing it) and we've decided on reading an ENV variable, and it should be managed by puppet

**Comment by davidschober** [comment]
@csyversen this is high-priority correct?

**Comment by csyversen** [comment]
We /could/ push to production without the environment variable being managed by puppet, but I'd really prefer it if it was. So yeah, high priority

**Comment by Toputnal** [comment]
Okay.  What is the Environment variable and where should it be set?  I'll add it to puppet.

**Comment by davidschober** [comment]
I'll send Jim the sidekiq pro email. is the env variable arbitrary? @bmquinn @csyversen @kdid

**Comment by bmquinn** [comment]
@davidschober I sent Jim the details earlier today. Should be g2g.

**Comment by davidschober** [comment]
cool. Sorry.

**Comment by davidschober** [comment]
@Toputnal is this done?

**Comment by Toputnal** [comment]
Note: set up bashrc for deploy user.   -- setup puppet to manage .bashrc one per environment and then use the existing puppet and then set that in hiera for custom environment variables per node .
