### ISSUE TITLE
formalize documentation for batch/ pub collections

### ISSUE THREAD

**Issue by davidschober** [nulib/images#283]
- [x] ensure public collections is documented
- [x] ensure batch import is documented
- [x] ensure sidekiq is documented

**Comment by davidschober** [comment]
@jenyoung is this done? I can't remember.

**Comment by jenyoung** [comment]
@davidschober please have developer look over these.

sidekiq guides  - https://github.com/nulib/images/wiki

batch import instructions https://northwestern.app.box.com/notes/94250229118
batch import testing https://docs.google.com/spreadsheets/d/1sLE_tzRCM-OgogJu9gciNJWDUKb5CTrbV2qyJ1KX0VA/edit
 
public collections guide https://northwestern.app.box.com/notes/103996500539
public collections testing https://docs.google.com/spreadsheets/d/16LdZTpUjc2fwgNo9SZoaEZM-emS9yJyV3MaZXKhVQT0/edit#gid=0

**Comment by davidschober** [comment]
Thanks Jen, 

Can you put links in the batch ingest instructions to the sidekiq errors? Also, maybe add a “gotcha” section for when things go wrong. I know that one thing that we’ve gotten hung up on before is people rerunning batches.

**Comment by kdid** [comment]
I think if you go through the process step by step and add some screenshots, xml samples,  and links, it would be helpful.

**Comment by jenyoung** [comment]
@Nic4Images - @davidschober and i were discussing documentation in general earlier today. let's discuss.
