### ISSUE TITLE
deploy "public" directory permissions changing

### ISSUE THREAD

**Issue by davidschober** [nulib/images#285]
The ownership of the capistrano releases folders /releases/#########/public is being changed to root. 

Cap can't set permissions like this. We think it's puppet.... Maybe because of the apache module? (similar structure). Can you look into it.

**Comment by Toputnal** [comment]
On what server?

**Comment by davidschober** [comment]
Sorry Jim, this is on images-s, images-p, menu-s, menu-p. The team has been deleting it manually to route around.

**Comment by Toputnal** [comment]
Fixed in puppet for menu-s, menu-p, images-s, and images-p
