### ISSUE TITLE
"rights statement" asks for login on public collections

### ISSUE THREAD

**Issue by davidschober** [nulib/images#286]
### Descriptive summary

When clicking "rights description" on public collection an error comes us asking for authentication. If a user is authenticated, the rights statement is not shown, but an odd framed page with a "you don't have permission to view this" error. . 
 
### Expected behavior
A user is shown the rights description for the collection. 

### Actual behavior
A user is asked for authentication or given an authentication error. 

### Steps to reproduce the behavior
* Go to images.library.northwestern.edu
* click on "rights description"
* see login in error
* login
* click on "rights description" 
* see auth error. 

### Screen shots

unauthenticated
![screen shot 2016-09-09 at 3 45 20 pm](https://cloud.githubusercontent.com/assets/4803230/18402321/7d552064-76a4-11e6-992e-61e4caa2d440.png)

Authenticated
![screen shot 2016-09-09 at 3 45 03 pm](https://cloud.githubusercontent.com/assets/4803230/18402310/7134fe4e-76a4-11e6-8a91-588e02509d5e.png)

**Comment by bmquinn** [comment]
Fixed and deployed.
