### ISSUE TITLE
Can't remove images from public collections (production)

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#287]
To recreate:

add images to public collection. 

try to remove images

see errors below in sidekiq. 

images are not removed from the public collection. 

From Sidekiq:

Arguments : "inu:dil-8dff15a2-2f39-496e-8a81-64da01291787", {"system_create_dtsi"=>"2015-01-22T23:55:30Z", "system_modified_dtsi"=>"2016-08-23T19:49:29Z", "object_state_ssi"=>"A", "active_fedora_model_ssi"=>"Multiresimage", "id"=>"inu:dil-3e085319-e225-44b8-b1e9-5c8d8996091a", "object_profile_ssm"=>["{\"datastreams\":{\"DC\":{\"dsLabel\":\"Dublin Core Record for this object\",\"dsVersionID\":\"DC1.0\",\"dsCreateDate\":\"2015-01-22T23:55:30Z\",\"dsState\":\"A\",\"dsMIME\":\"text/xml\",\"dsFormatURI\":\"http://www.openarchives.org/OAI/2.0/oai_dc/\",\"dsControlGroup\":\"X\",\"dsSize\":373,\"dsVersionable\":true,\"dsInfoType\":null,\"dsLocation\":\"inu:dil-3e085319-e225-44b8-b1e9-5c8d8996091a+DC+DC1.0\",\"dsLocationType\":null,\"dsChecksumType\":\"DISABLED\",\"dsChecksum\":\"none\"},\"RELS-EXT\":{\"dsLabel\":\"Fedora Object-to-Object Relationship Metadata\",\"dsVersionID\":\"RELS-EXT.7\",\"dsCreateDate\":\"2016-08-23T19:49:29Z\",\"dsState\":\"A\",\"dsMIME\":\"application/rdf+xml\",\"dsFormatURI\":null,\"dsControlGroup\":\"X\",\"dsSize\":1287,\"dsVersionable\":true,\"dsInfoType\":null,\"dsLocation\":\"inu:dil-3e085319-e225-44b8-b1e9-5c8d8996091a+RELS-EXT+RELS-EXT.7\",\"dsLocationType\":null,\"dsChecksumType\":\"DISABLED\",\"dsChecksum\":\"none\"},\"ARCHV-IMG\":{\"dsLabel\":\"Original Image File\",\"dsVersionID\":\"ARCHV-IMG.0\",\"dsCreateDate\":\"2015-01-22T23:56:28Z\",\"dsState\":\"A\",\"dsMIME\":\"image/tiff\",\"dsFormatURI\":null,\"dsControlGroup\":\"E\",\"dsSize\":0,\"dsVersionable\":true,\"dsInfoType\":null,\"dsLocation\":\"http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/production/RealVMC/COLLECTIONS/Naficy/inu:dil-3e085319-e225-44b8-b1e9-5c8d8996091a.tif\",\"dsLocationType\":\"URL\",\"dsChecksumType\":\"DISABLED\",\"dsChecksum\":\"none\"},\"ARCHV-EXIF\":{\"dsLabel\":\"EXIF Technical Metadata\",\"dsVersionID\":\"ARCHV-EXIF.0\",\"dsCreateDate\":\"2015-01-22T23:56:31Z\",\"dsState\":\"A\",\"dsMIME\":\"text/xml\",\"dsFormatURI\":null,\"dsControlGroup\":\"M\",\"dsSize\":15744,\"dsVersionable\":true,\"dsI...

error:

RuntimeError: inu:dil-0da8d6c0-3e01-43b7-b0a1-45a4c4a395c7 not found, skipping

**Comment by bmquinn** [comment]
Removed the duplicate Casas collection manually on production. This error was expected and correct in this situation, because of a race condition that occurred when the images were added to two different collections simultaneously. Without significantly changing this feature, the easiest solution to this problem is to make sure new institutional collections are created one at a time by verifying in the Sidekiq dashboard that there are no AddInstitutionalCollectionWorker jobs running in Sidekiq when creating a new collection (in "busy", "enqueued" or "retries").

**Comment by davidschober** [comment]
Sounds good. Let's close. @Nic4Images @jenyoung , and team, please document.
