### ISSUE TITLE
update email addresses on automatic emails

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#290]
Remove old email addresses from automatic emails,.

**Comment by csyversen** [comment]
hey @jenyoung , i just happened to run across this. Is this still an issue?

**Comment by jenyoung** [comment]
@csyversen i'm not sure. Am I supposed to get an email anymore when I upload a job into MENU? Because I didn't.

**Comment by csyversen** [comment]
@jenyoung I'm not sure what the deal is with email notifications and when they are supposed to be fired off, but i'm guessing the current behavior is ok if nobody has complained. Do you mind if i close this and we can open up another issue if we start running into problems?

**Comment by davidschober** [comment]
This was specific to auto-generated emails that were hard-wired (I think jl email was in there. I believe you cleaned it up.
