### ISSUE TITLE
Add Download Original Tiff for admins

### ISSUE THREAD

**Issue by davidschober** [nulib/images#291]
## DONE

A download tiff button is visible to admins that allows them to download tiff. 

Note, this should operate like the WWII posters does.

**Comment by davidschober** [comment]
Done by OCT 1.

**Comment by bmquinn** [comment]
@davidschober : @kdid and I looked into some more today, and found some serious blockers here that need to be discussed before merging this PR. The code here is fine, but we have issues with our ARCHV_IMG#location urls for possibly all images imported since they old synchronizer was shut down. There's going to be some data cleanup needed, and changes to our configs as well.

**Comment by davidschober** [comment]
Thanks for looking into this. Can one of you write up an issue with a  rough estimate of work needed?

**Comment by davidschober** [comment]
@jenyoung and nicole are going to dig into this more as well. Doing a quick spot check it seems as if many of these may be from the Rosenthal and Saskia collections. These either a) didn't have tifs or b) had tifs that were not imported. They were migrated from Mdid. They were missing in mdid. 

- [ ] Nicole and jen will do a deep dive and verify that that's what these are
- [ ] Team to discuss whether to keep or kill some of them. 

@kdid can we get a list of pids, location 

e.g. 

inu:dil-e480cd79-4e53-44fd-859a-d131feea5b04 | Philadelphia Museum of Art ; Rosenthal Art Slides ; DIL:inu:dil-e480cd79-4e53-44fd-859a-d131feea5b04 ; Voyager:310101

**Comment by kdid** [comment]
@davidschober 
In Steve's document, that @jenyoung attached to ticket #314, the "WWW.LIBRARY" tab has a list of pids with the library website as the tif location.

**Comment by kdid** [comment]
@davidschober - OK understand what you want. Will have tomorrow.

**Comment by davidschober** [comment]
We can talk more tomorrow. What I'm looking for is what's exposed as "location" in the fe of images. Not sure if it's named the same on the backend.

**Comment by kdid** [comment]
Opened ticket with devops: https://github.com/nulib/devops/issues/29

**Comment by kdid** [comment]
@jenyoung and @Nic4Images - the status of this is that the download button is  on staging, but we are waiting on @d-venckus or @Toputnal to take a look https://github.com/nulib/devops/issues/29 so that the tifs on staging will be accessible. (Right now the app will correctly display an error message since it can't find the tif). Once they've addressed that, we will need to update some configs and then it should be testable.

**Comment by kdid** [comment]
@Nic4Images and @jenyoung -
The TIF button can be tested now on staging. Should work for any new images you add/import. (The old images in there should show examples of error conditions) I tested one through batch and seems OK.

In addition to error conditions be sure to test correct behavior of all buttons for authenticated/unauthenticated and authorized/unauthorized users. 
Thanks!

**Comment by jenyoung** [comment]
tested Tif button with batch imported record. All passed.

**Comment by davidschober** [comment]
@Nic4Images can you give final sign off?

**Comment by Nic4Images** [comment]
Hi, I tried downloading a Tiff and it spun. There seemed to be a connection issue here.

**Comment by egilchrist** [comment]
Finished testing a small batch and image on Staging.  I was able to download a Tiff for both on Staging.

**Comment by kdid** [comment]
Great, I think we are just waiting on sign-off from @Nic4Images then.

It looks like the server unresponsiveness/performance issue that Nicole (and I) experienced when using the tif button was related to trying to use it while alot of image conversions were happening. For example, trying to use the Download Tif button on an image page that is being viewed for the first time after being imported through batch import. Production has more resources than staging - so may not be as affected by this -  but this known issue is something to keep in mind during testing.
