### ISSUE TITLE
Alternate titles in the Title: not Alternate title:

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#295]
### Descriptive summary

Alternate titles in the Title: not Alternate title:
### Expected behavior

Alternate titles should only display in Alternate title:
### Actual behavior

For some records in all collections in Images, the alternate title is appended to the Title field, separated by a semicolon.

There are records in Images which have alternate titles that display correctly. 

![screen shot 2016-06-27 at 2 11 11 pm](https://cloud.githubusercontent.com/assets/2250501/18477834/ac665164-7994-11e6-816f-69eba87a7181.png)

![2016-09-13_083516](https://cloud.githubusercontent.com/assets/2250501/18477865/ca76dc46-7994-11e6-8f23-561a39f275ea.jpg)

**Comment by davidschober** [comment]
@jenyoung It sounds like this was a purposeful decision. Let's talk this through.

**Comment by davidschober** [comment]
@jenyoung I think the last time we talked we decided we weren't going to change this in the current version of the application. Closing.
