### ISSUE TITLE
null error upon publish for jobs 11701, 11735

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#296]
### Descriptive summary

Images in two specific jobs, 11701 and 11735, are giving a null error upon publish. The images are actually published to Images but are not removed from MENU.

Having said that, two records in test job 456 were published to images. One went through fine, the other threw the null error. Both tifs came from job 11735.

Other jobs have been completed without errors.

Erin reported this error to me - she was able to successfully publish records without errors in job 11735 till about 10 am.

### Expected behavior

Images should publish to Images and be removed from MENU upon publish.

### Actual behavior

Images are being published to Images -- but throwing a null error and not being removed from MENU.

I also noticed that the error records in 11701 are missing the Description element in Images. They are in the metadata in MENU. 

error message: 

![2016-09-13_113947](https://cloud.githubusercontent.com/assets/2250501/18482765/20a308a8-79a7-11e6-80b6-c09eacca32a9.jpg)

record in Images:
https://images.northwestern.edu/multiresimages/inu:dil-36922b80-242c-4e8a-bef9-51b395fef2be

Other records that have this issue;

11701
https://images.northwestern.edu/multiresimages/inu:dil-36922b80-242c-4e8a-bef9-51b395fef2be
https://images.northwestern.edu/multiresimages/inu:dil-9d7cdb90-253d-4335-8a99-ac5d7cb443f9

11735
https://images.northwestern.edu/multiresimages/inu:dil-c6cbcdc5-4910-4bfb-92ea-aa2627024792
https://images.northwestern.edu/multiresimages/inu:dil-283303b0-ef9d-4e00-89d9-0b66cd0963a8

456
https://images.northwestern.edu/multiresimages/inu:dil-5ac8af66-2fc9-4f2f-8efe-955a7f7a1375

A sample of the records Erin successfully published from job 11735
https://images.northwestern.edu/multiresimages/inu:dil-444ccc73-859d-419e-b6c6-665e350c3d77
https://images.northwestern.edu/multiresimages/inu:dil-a19dd678-2be6-4c89-b573-7f3a2e7f7de6

### Steps to reproduce the behavior

1. Edit metadata in jobs 11701, 11735
2. Publish image
3. Null error should appear
4. Search Images to find record.

**Comment by bmquinn** [comment]
Sounds like this was a problem with the browser session that was fixed with a reboot. If it keeps occurring we'll re-open the issue.

**Comment by bmquinn** [comment]
Whoops wrong issue. Re-opening, sorry.

**Comment by jenyoung** [comment]
Erin tried publishing an image in job 11735 that didn't have pre-existing metadata in it and still got the null error.  this is that record https://images.northwestern.edu/multiresimages/inu:dil-7e65e75d-99f3-419e-aa57-966b772927a9

**Comment by jenyoung** [comment]
After talking more to David, going to test 10 more records, verifying that we can edit these records once published, and that they show in fedora. 

A possible way forward is to publish these images and then go back and delete them from MENU.

**Comment by davidschober** [comment]
@jenyoung to test and close.

**Comment by davidschober** [comment]
@jenyoung can we go ahead and close this?

**Comment by jenyoung** [comment]
@davidschober This is still happening - and is happening for other saved jobs in MENU. They do eventually get published into Images, sometimes after a couple of tries. I'm ok with closing for the old saved jobs. I will create a new bug card if it starts happening for newly imported into MENU jobs.

**Comment by davidschober** [comment]
I think that's a good plan
