### ISSUE TITLE
redirect African Maps Alma handles to images records

### ISSUE THREAD

**Issue by davidschober** [nulib/images#299]
### Descriptive summary

We’re getting ready to move the African Maps images into Images. These also have records in ALMA with handles. We need to redirect the Alma handles to point to new records. 
### Expected behavior

Alma handles redirect to new African Maps images records
### Questions:

What does the dev team need from @jenyoung and team to make this happen?

**Comment by davidschober** [comment]
@jenyoung I moved this here so we could track.

**Comment by davidschober** [comment]
@bmquinn @csyversen @mbklein @kdid can someone let Jen know what she needs to collect to make this happen?

**Comment by jenyoung** [comment]
this will be a public collection in Images if that helps.

**Comment by jenyoung** [comment]
fyi , i'm hoping to do the ingest before thanksgiving or the week after.

**Comment by davidschober** [comment]
@csyversen can you let Jen know what she needs to collect?

**Comment by csyversen** [comment]
so my memory of this is kind of fuzzy, but all we should need to do is to update the handles so they no longer point to they do currently and they point to their new destination in images. 

so i'd need a list of handles (something like 2166.DL/inu-blah-blah) and then the corresponding pid for that record.

**Comment by jenyoung** [comment]
related work #307

**Comment by csyversen** [comment]
related #307 , but once the records have been ingested into images and i get a list of handles and their new updated URLs in images I can go ahead and update the handles themselves. (i'm also going to cross post this in the other issue)

**Comment by jenyoung** [comment]
#307 closed. no longer need handles for fava

**Comment by csyversen** [comment]
hey @jenyoung , i just wanted to follow up on this issue. We were holding off on importing the african map collection for some reason?

**Comment by jenyoung** [comment]
@csyversen wanted to upload them on staging first to make sure none of the images are too big and that the metadata was correct. that's where  the vra display and vrawork bugs came from and why i wanted to wait till staging was cleared out

**Comment by csyversen** [comment]
ah cool, thanks for the update! I'll leave this ticket alone until we're ready to get to it then!

**Comment by jenyoung** [comment]
i'm having @egilchrist start working on matching these this week.

**Comment by jenyoung** [comment]
@csyversen this done! the spreadsheet of handles and pids: 
[Afri_maps_handles.xlsx](https://github.com/nulib/images/files/984440/Afri_maps_handles.xlsx)

**Comment by csyversen** [comment]
awesome, thank you @jenyoung ! I'm out at a training this week but I'm back on Friday and I'll try to get to it then!

**Comment by csyversen** [comment]
done! I spot checked ~15 handles and they are all resolving properly

**Comment by csyversen** [comment]
(also for future reference, the provided spreadsheet was great and had everything we needed on it)

**Comment by davidschober** [comment]
Awesome.
