### ISSUE TITLE
Perceived slowness when loading images

### ISSUE THREAD

**Issue by davidschober** [nulib/images#300]
### Descriptive summary

Perceived slowness on certain images. We can't seem to tell if certain images are not caching properly (RIIIF) or if the cache is being trashed on each deploy. BQ thought maybe we could persist the tmp directory through deploys. Or is the cache clearing prematurely 

### Expected behavior

Images after being being hit once should have tiles cached and should load quickly. 

### Actual behavior
Individual images are at times loading to a blank page for > 10 seconds. It seems that this might be occurring even after hitting the image, but that is a bit unclear.

**Comment by davidschober** [comment]
adding a bug label. On some images, some of the image tiles are throwing 500s

e.g. http://images.library.northwestern.edu/multiresimages/inu:dil-266e8cb8-bfb2-4628-96e5-f6f8a7756f15
![screen shot 2016-09-22 at 3 32 53 pm](https://cloud.githubusercontent.com/assets/4803230/18765305/b6110efa-80da-11e6-994b-0e7a1f6c511c.png)

![screen shot 2016-09-22 at 3 38 36 pm](https://cloud.githubusercontent.com/assets/4803230/18765294/a9f8ce00-80da-11e6-8237-5b805ab4c0f3.png)

**Comment by bmquinn** [comment]
Looks like these are OpenJP2 conversion errors: 

```
I, [2016-09-22T16:19:01.596405 #46888]  INFO -- : method=GET path=/image-service/inu-dil-266e8cb8-bfb2-4628-96e5-f6f8a7756f15/8192,8192,3337,1076/418,/0/default.jpg format=jpeg controller=riiif/images action=show status=500 error='RuntimeError: Unable to execute command "convert -crop 3337x1076+8192+8192 -resize 418 /var/www/html/dimages/inu-dil-266e8cb8-bfb2-4628-96e5-f6f8a7756f15.jp2 jpg:-"
convert: Failed to decode the codestream in the JP2 file
```
![screen shot 2016-09-22 at 4 21 45 pm](https://cloud.githubusercontent.com/assets/1395707/18766686/0f181970-80e1-11e6-8da7-46e5ef0359dc.png)

I refreshed the page a few times and everything eventually worked. I think we're probably pushing the limits of performance with the conversions.

**Comment by davidschober** [comment]
OK. I'm going to tag this for a discussion.

**Comment by davidschober** [comment]
closing as dupe
