### ISSUE TITLE
Expose Collection Description field as a live link under Right Description.

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#302]
### Users would like to have a description and rights visible at the collection level.

On the HP Please change the "Rights Description" link to "About this Collection"

The model popup should include the collection description copy as well as the rights statement.

example below

------
## Collection Description

Text here from the collection description field. 

## Rights Statement
Text here from the rights statement.

**Comment by Nic4Images** [comment]
![screen shot 2016-09-22 at 2 54 49 pm](https://cloud.githubusercontent.com/assets/20801226/18765593/ff06054c-80db-11e6-918b-59a84c3ec563.png)
![screen shot 2016-09-22 at 2 58 50 pm](https://cloud.githubusercontent.com/assets/20801226/18765598/05c96036-80dc-11e6-89c8-0ffc0e8564b9.png)

**Comment by Nic4Images** [comment]
Added note : can the space for adding this at the Admin level be increased to match that of the Rights Description - as you can see in the screenshot above it is difficult to see what you have written with only one line visible. Thanks, N.

**Comment by davidschober** [comment]
@Nic4Images I think it will look odd to have two links under the the thumbnail. Can we combine the two into a single "Collection Information" or and "about this collection" link which would display **both** the rights description and the collection description in a popup?

**Comment by Nic4Images** [comment]
I think they need to be separate as they serve different purposes - that said the idea of having a "About this collection" both as popups sounds great!

**Comment by Nic4Images** [comment]
I should say with both as pop ups under the About this collection = great

**Comment by davidschober** [comment]
I’m not sure I’m following. I’m saying a single link that would open a single display popup with a collection description and a rights statement. How we record/store data  can remain the same.

**Comment by davidschober** [comment]
OK. After a brief discussion we decided to have a single "about this collection" which will pop open a model containing:

**Collection Description**
[the collection description field text]

**Rights Description**
]The rights description field text]

**Comment by Nic4Images** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/20801226/18790735/80d89f82-8175-11e6-88f5-cd90faf5037a.jpg)

**Comment by Nic4Images** [comment]
Carolyn and I agreed on the titles of those two "fields" yesterday so we can run with them.

**Comment by davidschober** [comment]
@kdid Can you grab this next week? I'd like to get this and the tiff download done early October.

**Comment by kdid** [comment]
Yes, I'll pick up next week though deployment still blocked by #312

**Comment by davidschober** [comment]
Awesome. Thanks!
