### ISSUE TITLE
duplicate images being published from MENU with same accession number.

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#304]
### Expected behavior

Records should be rejected with the same Accession number. 
### Actual behavior

From a new job, two images were published twice.

Search "320606" and "320609" in Images -- there should only be one image. There are two. 

320606
http://images.northwestern.edu/multiresimages/inu:dil-eec4ecf8-6257-4bfa-8770-5f69fbaca334
http://images.northwestern.edu/multiresimages/inu:dil-2a57db72-8a9a-47a8-bdf9-c7ffaa17b227

320609
http://images.northwestern.edu/multiresimages/inu:dil-27fd3a8a-5bf9-4f78-88d7-eeeacb81cf13
http://images.northwestern.edu/multiresimages/inu:dil-2a57db72-8a9a-47a8-bdf9-c7ffaa17b227

**Comment by davidschober** [comment]
@jenyoung can you verify this in staging as well.

**Comment by davidschober** [comment]
Fixed.
