### ISSUE TITLE
Fava Masks handles

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#307]
### Descriptive summary

We’re getting ready to move the Fava Masks images into Images. These also have records in ALMA with handles. We need to redirect the Alma handles to point to new records.

I will also need 10 new handles for the side views of the masks. 

Site: http://digital.library.northwestern.edu/fava/masks.html
### Expected behavior

Alma handles redirect to new Fava Masks images records.

**Comment by csyversen** [comment]
related #299 , but once the records have been ingested into images and i get a list of handles and their new updated URLs in images I can go ahead and update the handles themselves. (i'm also going to cross post this in the other issue)

**Comment by jenyoung** [comment]
@csyversen some of these will need totally new handles as well.

**Comment by csyversen** [comment]
@jenyoung i *think* that's easy enough. once they are in images and have a URL we can create handles for them

**Comment by jenyoung** [comment]
great. just didn't want to lose sight of that part. @csyversen

**Comment by jenyoung** [comment]
these handles won't be needed after all. Dan wants to remove the links from ALMA. I will get @csyversen a list of handles to be deleted once migration is complete.
