### ISSUE TITLE
Cannot open single item/record/image view on mobile.

### ISSUE THREAD

**Issue by ccaizzi** [nulib/images#311]
85% sure this was working before the UTF-8 bug fix.

On my iphone, after I perform a search, tapping on an image or title does not open the single page view.  I saw a similar problem on Cara List's mobile device in the public demo. Single item view in AVR works on my iphone.

**Comment by ccaizzi** [comment]
all, just parking this here.  it may not even be worth working on.  will need to discuss with david.

**Comment by davidschober** [comment]
@ccaizzi mobile is around %14 of our users 480ish a month. I would argue to punt.

**Comment by davidschober** [comment]
ambandoning.
