### ISSUE TITLE
Install Varnish

### ISSUE THREAD

**Issue by davidschober** [nulib/images#313]
### Descriptive summary

We would like to install varnish on images (s and p)
### Expected behavior

Public pages are cached.

ensure /image-service/*.jpg

is being cached.

**Comment by davidschober** [comment]
a full jpg is https://images.northwestern.edu/image-service/inu-dil-b49c918b-d945-4905-ba63-f668157885e2/square/,300/0/default.jpg

**Comment by davidschober** [comment]
stuff we will need to look at... Removing cookies from requests to 

http://images.northwestern.edu/image-service/

https://varnish-cache.org/trac/wiki/VCLExampleCacheCookies 

Make sure that our IPs can purge the cache using curl in case of emergency.

**Comment by davidschober** [comment]
@d-venckus can you share the config and let us know when you're ready to test?

**Comment by ccaizzi** [comment]
@davidschober we decided to pull back on this, correct?

**Comment by davidschober** [comment]
It is not priority with all the other priorities on the board (there’s a lot)

**Comment by davidschober** [comment]
closing. While varnish may cover up the problem a bit. It's becoming increasingly obvious that we will need a full-fledged image server (loris, iipimage, cantaloupe) for images that are very large.
