### ISSUE TITLE
Change configuration for archive image

### ISSUE THREAD

**Issue by davidschober** [nulib/images#316]
### Descriptive summary

Currently the archive image location is configured wrong causing some bad data. Update it to the proper location.

repo_url: http://repository.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/images/

should be: 

http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/images/
related to #314

**Comment by bmquinn** [comment]
Deployed and tested on production.
