### ISSUE TITLE
install OAI/PMH images

### ISSUE THREAD

**Issue by davidschober** [nulib/images#320]
Install for fedora 3.8.1...

Note, DV will investigate whether the issue with OAI/PMH on fedora 4.0 (IR) is released to the version. 

related to https://github.com/nulib/institutional-repository/issues/9

**Comment by davidschober** [comment]
OAI verbs https://memory.loc.gov/ammem/oamh/oai_request.html

It seems to be on, but maybe we need more config to expose collections.

**Comment by davidschober** [comment]
OK it looks like this is running. Verbs respond.

david.schober [12:38 PM]  
http://repository.library.northwestern.edu/fedora/oai?verb=Identify

david.schober [12:44 PM]  
http://repository.library.northwestern.edu/fedora/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:example.org:inu:dil-5f4c79ec-9f65-4e41-88aa-b4f1e128829b

david.schober [12:50 PM]  
http://repository.library.northwestern.edu/fedora/oai?verb=GetRecord&metadataPrefix=oai_vra&identifier=oai:example.org:inu:dil-5f4c79ec-9f65-4e41-88aa-b4f1e128829b

[12:53]  
http://repository.library.northwestern.edu/fedora/oai?verb=ListMetadataFormats

**Comment by davidschober** [comment]
Some side notes: We need to change our repository from example.org to our full repository name. Also @mbklein have you ever added extra metadata prefixes to a fedora OAI provider? I'm assuming it's in a config somewhere.

**Comment by davidschober** [comment]
@jenyoung can you OK to close per our conversation? I think we can make a separate ticket to make this public later.

**Comment by rtrautve1** [comment]
#25

**Comment by jenyoung** [comment]
OAI-PMH is up and only doing DC. Will have to investigate further for pushing out VRA. Going ahead and closing now.
