### ISSUE TITLE
4410 tif's with ARCHV_IMG location .../farchive13/inu-dil/hydra/test either missing or can't access via url

### ISSUE THREAD

**Issue by kdid** [nulib/images#322]
There are a few related parts to this issue:
(examples of pids not included in GitHub issue)

**1) 3367 tifs missing**
3367 images that were added to images between 2015-07-09 - 2016-03-01 have `http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/test/` + `pid.tif` for the ARCHV_IMG location.

The tifs are not present in `/farchive/farchive13/inu-dil/hydra/test`

Here is a link to these 3367 pids/locations in Box: https://northwestern.box.com/s/w1k2zmbzxmijk6wowecth670ktscnkaf

**2) 447 tif's missing**
1043 images that were added to images between 2016-03-01 and 2016-05-04, have ARCHV_IMG location of `http://repository.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/test/` + `pid.tif`, 

Only 596 of those tifs are present in `/farchive/farchive13/inu-dil/hydra/test`

**3) 596 tifs not accessible via ARCHV_IMG url**
For the tif's that are present with the ARCHV_IMG location of `http://repository.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/test/` + `pid.tif` - are not accessible at that location. With the current configuration, they can be accessed at: 
`http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/test/` + `pid.tif`

Here is a link to the pids (1043) from both parts 2 and 3 combined. (447 + 596 pids)
https://northwestern.box.com/s/a28m1sja6tfjq6bgxni5hbwalijso73w

This is related to (part of) issue #314

**Comment by davidschober** [comment]
I started spot checking on a hunch. It seems as if the type in #1 and #2 are accessible here (although we have the same permission issue as the 70k): http://rstorage.library.northwestern.edu/farchive/farchive13/inu-dil/hydra/production/PID.tif

**Comment by Toputnal** [comment]
See my comments on 323.  This rings a bell for a change that was made by hand a while a go.

**Comment by jenyoung** [comment]
Nicole and I will review spreadsheet.

**Comment by davidschober** [comment]
@Toputnal can you randomly grab a handful of PIDs ~10 from the referenced box folder and search across rstorage (or other old repo storage locations) to see if we can find them? We're looking for a pattern.

**Comment by Toputnal** [comment]
I ran a check against ALL of the 3367 PIDs here searching on both farchive8 and farchive13 and found ZERO of these PIDs. cc: davidshober

**Comment by davidschober** [comment]
Thanks @Toputnal.

**Comment by Toputnal** [comment]
Ditto on the second batch of 1,043 PIDs.  Not on farchive8 or farchive13.

**Comment by davidschober** [comment]
@Toputnal 596 of the 1043 tifs are present in /farchive/farchive13/inu-dil/hydra/test, correct?

**Comment by kdid** [comment]
@Toputnal, have you tried subbing a dash for a colon in the tif name? I put an example in slack, images channel just now.

**Comment by Toputnal** [comment]
Please see results here:  https://northwestern.app.box.com/notes/101502367807
and here: https://northwestern.app.box.com/notes/101501262573

**Comment by kdid** [comment]
Closing. Jim B. attached links to list of missing and found files for the record.

**Comment by davidschober** [comment]
Adding an issue for Jen and team to work with the records with no matching tifs.
