### ISSUE TITLE
Investigate correct use of jhove during batch ingest

### ISSUE THREAD

**Issue by kdid** [nulib/images#329]
Investigate whether batch ingest, where 25 jobs may be trying to share the same jhove.xml file may be leading to incorrect metadata or other problems.

## Done 

- [ ] Confident in our use of batch ingest and jhove
- [ ] issues written if necessary.

**Comment by davidschober** [comment]
@kdid I'll move this to ready. I'll assign you, but grab the team. It sounds like this is mostly investigative at this point?

**Comment by davidschober** [comment]
is this still relevant?

**Comment by kdid** [comment]
I think we opened the ticket knowing this was an issue we might not fix but to keep it tracked. Yes, it's still an issue. But we can close as "Known Issue" if we don't want to fix now.

**Comment by davidschober** [comment]
closing as known issue.
