### ISSUE TITLE
Figure out group permissions needed for Temp

### ISSUE THREAD

**Issue by davidschober** [nulib/images#330]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

Newly added temp workers can't access images. Is there an LDAP group that we need them to be added to in order to get the same permissions as say Dru. 

### Expected behavior
User can login and do administrative tasks like Dru

### Actual behavior
User is unable to login

### Steps to reproduce the behavior
1. Have temp login
2. see that they don't have access

### Note

Stork noticed the following: 

Bad:
INFO -- : method=POST path=/users/auth/ldap/callback format=html controller= action= status=302

Good:
INFO -- : method=POST path=/users/auth/ldap/callback format=html controller=users/omniauth_callbacks action=ldap status=302

**Comment by davidschober** [comment]
A little more info here. Dru is a "normal" user not an admin. He can login and see collections via the front end. It seems as if temp employees do not have complete records (e.g. some fields like phone, etc are missing).

**Comment by csyversen** [comment]
try changing images-s' ldap server to the new AD server (that's used in menu)

**Comment by davidschober** [comment]
OK. I tried the temps login on 

Images -- No good
Menu  -- Works
Avalon -- Works
arch -- no good

Arch and images are using registry for the AD server. Can we tweak the config to try the other server (preferably on Monday after Thanksgiving...)

**Comment by davidschober** [comment]
Todo:

- [ ] swap with the ldap server avalon is using in test
- [ ] verify temp style netIDs work.
- [ ] push to production. 
- [ ] possibly standardize arch on same ldap?

**Comment by csyversen** [comment]
working on this

**Comment by csyversen** [comment]
i did a bunch of experimenting today and tried using menu's staging configs and no dice. We might have to talk to devops to learn more about our ldap/AD set up

**Comment by davidschober** [comment]
Chris moving this to in progress.

**Comment by davidschober** [comment]
@csyversen can you review the stork/ jen email string?

**Comment by csyversen** [comment]
Yep, reviewed.

We roped in MBK to help out and figured out that menu and images are doing authentication slightly differently. Images is using omniauth and menu is using devise-authenticatable. So somewhere in there (and also possibly in the differing configs) is what we'd have to fix. 

That's not a quick and easy change though, it'd require some developer thought and time.

**Comment by jenyoung** [comment]
Going to go ahead and close. Thanks for investigating. Need to remember this for nextgen so temps can login to that system.  We'll continue to login temps daily.
