### ISSUE TITLE
Possible problem with Sidekiq start/stop scripts

### ISSUE THREAD

**Issue by kdid** [nulib/images#333]
We noticed that Sidekiq is not running on 11/22/2016 on images-s, so there may be an issue with the scripts implemented in this issue:

https://github.com/nulib/images/issues/247

**Comment by davidschober** [comment]
@kdid This was made redundant with @d-venckus 's start stop scripts (work done via  #99 and #20)

**Comment by kdid** [comment]
This ticket is images not ARCH though. I think the issue is that if sidekiq dies for some unknown reason, it's not restarted - which is what happened when this issue was opened.  But starting and redeploying the application and server reboots are working fine.

**Comment by davidschober** [comment]
Apparently I have arch on the brain. Let's leave this closed and open a new one if need be.
