### ISSUE TITLE
Cannot publish NOR edit anything on production

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#337]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

Cannot publish NOR edit anything on production. Started at about 9:30 AM. 11/29.

### Expected behavior

Editing and publishing records should work. 

### Actual behavior

Editing a record - upon publish, get a "null" error.

Publishing a new record "See logger for details. New Record not published."

**Comment by davidschober** [comment]
pulled back changes in issue #338.

**Comment by davidschober** [comment]
@jenyoung and erin, can you verify

Does staging currently work
- [ ] Yes
- [ ] nope

After deploy on Wednesday we tested in production and everything worked
- [ ] yes
- [ ] no

Monday (or early Tuesday), we were publishing in production **and then** the system broke around 10:30am
- [ ] yes
- [ ] no

Go ahead and check the boxes, then add any notes in a new comment.

**Comment by jenyoung** [comment]
i wasn't asked to do a full blown test on production so i don't think i did. i feel like i edited a record though to make sure the facet updating happened. 

editing and publishing  were done by erin and others on production after the change was pushed wed. afternoon.  all was good until erin tried to publish an edited record at about 9:30 am yesterday.

**Comment by jenyoung** [comment]
images staging issues:

can neither create a new group nor delete an old one.  trying to create a powerpoint just has the wheel spinning for at least 10 minutes.

**Comment by jenyoung** [comment]
menu staging issues;

can neither edit an exiting record nor publish a new one. getting the same errors that started on production yesterday.

publishing a new record

![2016-11-30_110557](https://cloud.githubusercontent.com/assets/2250501/20763404/8964a308-b6ef-11e6-9b00-151ad0b55c60.jpg)

editing an existing record

![2016-11-30_110653](https://cloud.githubusercontent.com/assets/2250501/20763416/92520230-b6ef-11e6-8ced-1d50b2b33692.jpg)

**Comment by davidschober** [comment]
Just to be clear, did you have someone roll through the whole script on production as well @jenyoung

**Comment by jenyoung** [comment]
@davidschober right now? no. and not on wednesday either.

**Comment by davidschober** [comment]
@jenyoung closing as this is resolved.
