### ISSUE TITLE
Recent commits had to be reverted

### ISSUE THREAD

**Issue by csyversen** [nulib/images#338]
### Severity - medium?

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

### I had to revert the last two commits to images and redeploy
For some reason it was stopping Jen and Erin from editing or publishing new images. We'll have to take a look at those changes and make sure we run them through the wringer on staging

**Comment by davidschober** [comment]
Note, after testing in #337, we will break out tasks if necessary.

**Comment by jenyoung** [comment]
related #293
