### ISSUE TITLE
cannot publish my batch job to images-s

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#340]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

Job isn't been seen even though it's in the correct folder. Was able to batch import both the "11741" and "small_test_batch_2" folders. Wanted to test the African Maps files before I batch ingest them into production.

### Expected behavior

job is seen and imported.

### Actual behavior

![2016-12-05_183244](https://cloud.githubusercontent.com/assets/2250501/20908293/6fd4c840-bb19-11e6-854f-ff98a7e69780.jpg)

![2016-12-05_183450](https://cloud.githubusercontent.com/assets/2250501/20908313/9e369b8c-bb19-11e6-9836-b25fe2ef0dff.jpg)

### Steps to reproduce the behavior

1. Try to batch import this job.

**Comment by kdid** [comment]
@jyo, I don't see the directory 'maps_test_1' on the staging dropbox, I see it on the production dropbox.

Can you clarify where you are trying this?

**Comment by jenyoung** [comment]
@kdid i thought the staging dropbox and production dropbox were one now. where is the staging dropbox?

**Comment by davidschober** [comment]
Closing for now. The images staging dropbox is on po. @jenyoung can you post the full path when you get a chance just so we have a record.
