### ISSUE TITLE
staging rejecting filenames

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#341]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

tried to batch import the 296 files on po\Dropbox-Images-Menu-Staging\batches\maps_test_1  
error given:  Invalid File Names -- all files listed as invalid.

moved one tif to jy_test, tried to import thru menu-s and received email "Hello, the files jy_test/inu-afrmap-3797124-recto-master.tif did not get imported into Menu. "

also tried batch ingesting batches\11741 - that worked like normal except it didn't move the job to completed or remove the images from the job folder.

### Expected behavior

files are ingested.

### Actual behavior

they're not.

### Steps to reproduce the behavior

1. Try to batch import my job -po\Dropbox-Images-Menu-Staging\batches\maps_test_1

**Comment by davidschober** [comment]
We will dig into the other parts of this. But the _completed folder is not being used anymore. That change occurred during our last big push. Having menu and images independently manage files was causing serious issues. Can you make sure the documentation gets updated to call that out?

>>> also tried batch ingesting batches\11741 - that worked like normal except it didn't move the job to completed or remove the images from the job folder.

**Comment by davidschober** [comment]
Tested on staging with a small batch.

Bad accession numbers/dupes acted as expected.
good accession were imported 

> Test batch = "/Dropbox-Images-Menu-Staging/batches/dssmallbatch"
> imported image https://images-s.library.northwestern.edu/catalog?utf8=✓&q=david_test+2+batch. 

I will rework african map test (a small run with unique filenames)

**Comment by davidschober** [comment]
Did another round of tests. Renamed african maps files and tested two sets of xml.

## TEST 1

* Tested two with original filenames

### Results
 Both failed with
![screen shot 2016-12-07 at 2 29 02 pm](https://cloud.githubusercontent.com/assets/4803230/20991249/03addd6a-bca3-11e6-9cca-fe2be0899c3e.png)


## Test 2:

Renamed files, tested one with afrimap xml, one with test dataxml. 

* test batch: /Dropbox-Images-Menu-Staging/batches/dsafrimap
* assets: afrimap1 (original tiff, afrimap xml, new accession), afrimap2 (original tiff, batch text xml)

### Results

* afrimap1 fails with "No accession"
* afrimap2 clears through https://images-s.library.northwestern.edu/multiresimages/inu:dil-4344b59b-048a-4614-9f1c-d79603b2749b

TODO:

- [ ] check xml @jenyoung 
- [ ] Check filenames @csyversen or @kdid anything jumping out?

**Comment by jenyoung** [comment]
i figured out why afrimap1 fails with no accession. i need to correct my xml files. however, once i got the xml to pass, now the image is failing with "not an image type"

**Comment by jenyoung** [comment]
did another test with my corrected xml -- jy_afri_small. left the hyphens in the filename - it fails with "invalid filename". changed the hyphens to underscores, filename passes but getting another error that the tiff is not an "image type"

**Comment by kdid** [comment]
@jyo, the file `/dropbox/batches/jy_afri_small/inu_afrmap_3797082_recto_master.xml` is throwing the "not an image type" error because it is failing this test: `vra.xpath("/vra:vra/vra:image").present?`

I looked at the xml file in dropbox and it looks to be a work xml file not an image file?

```
<?xml version="1.0" encoding="utf-8"?>
<vra:vra xmlns:vra="http://www.vraweb.org/vracore4.htm"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:fn="http://www.w3.org/2005/xpath-functions"
         xmlns:marc="http://www.loc.gov/MARC21/slim"
         xmlns:mods="http://www.loc.gov/mods/v3"
         xsi:schemaLocation="http://www.vraweb.org/vracore4.htm http://www.loc.gov/standards/vracore/vra-strict.xsd">
   <vra:work id="inu-dil-9937970824202441_w" refid="inu:inu-dil-9937970824202441">

<!--Agents-->
      <vra:agentSet>
         <vra:display>Mercator, Gerard, approximately 1565-1656 ; Mercator, Gerhard, 1512-1594</vra:display>
         <vra:agent>
...
   </vra:work>
</vra:vra>
```

**Comment by jenyoung** [comment]
i have to investigate as to why my xslt is creating them as work records and not image records. i'm going to close assuming that there are no actual issues with the filenaming.

**Comment by jenyoung** [comment]
i'm using the xslt that we use for ingestion into images from menu which creates a work. it's overcomplicating the issue and i just need to have it create an image record.
