### ISSUE TITLE
Problem with log rotation on staging

### ISSUE THREAD

**Issue by kdid** [nulib/images#342]
The application isn't able to write log files - log rotation is setting file ownership to root.

**Comment by kdid** [comment]
And permissions s/b 0666. 

The application is not working.

**Comment by davidschober** [comment]
@d-venckus and @Toputnal let us know when you have an update.

**Comment by Toputnal** [comment]
Hi @kdid is this on images-s?  Which log files cannot be written?  Who is supposed to own the log files?

**Comment by kdid** [comment]
/var/www/dil_hydra/shared/log

Compare with production
