### ISSUE TITLE
wipe files in images-s

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#344]
if it's not terribly time-consuming, it'd be helpful if images-s is wiped - all files removed from the app. thanks!

**Comment by davidschober** [comment]
@csyversen said he's going to steal MBK's wipeout script from 
https://github.com/avalonmediasystem/avalon/issues/1363

**Comment by davidschober** [comment]
@csyversen ported the wipeout task. When ready, we can run. @kdid do you have any other concerns?

**Comment by kdid** [comment]
Nope -just a note that the DIL institutional collection (and WWII if it is needed), need to be manually created by a dev afterward with the same pid it has in the config.
