### ISSUE TITLE
display issues with batch import on staging

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#349]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

Record has been changed to only be a vra:image. RelationSet added.
Batch importing is working -but now there's weird display stuff happening.
Fields are being displayed multiple times. 

https://images-s.library.northwestern.edu/multiresimages/inu:dil-975a5993-147b-4c08-b923-a8f330e5f208

this one i imported with all of the display fields filled out -- same thing happened here.
https://images-s.library.northwestern.edu/multiresimages/inu:dil-8006f65f-3556-42f3-85e8-ba081b5c83f3

the facets are beautiful though!

### Expected behavior

the display only displays things once.

### Actual behavior

displays are being repeated multiple times.

### Steps to reproduce the behavior

1. jy_afri_small folder
..

**Comment by davidschober** [comment]
@jenyoung Let's see if we can trouble shoot this together. I have some time after a 10am.

**Comment by kdid** [comment]
@jenyoung - is batch uploading xml containing `<display>` elements something that was ever tested in regards to batch? 

Looking through the existing xml for batches  previously uploaded on staging (and production) I don't see any xml with these elements (obviously I can only see what remains on the server which isn't a ton).

**Comment by davidschober** [comment]
closing. This should be handled in #350.
