### ISSUE TITLE
Images not handling display elements in VRA during batch ingest

### ISSUE THREAD

**Issue by kdid** [nulib/images#350]
Updating DONE looks like 1/12/2017 since the comments on this ticket may have gotten confusing:

DONE:
- [x] Fix validation check of VRA (both work and image) after it is transformed so that invalid VRA does not go into Images.
- [x] (new feature) If display element for an element set  is provided and is not empty, use it. Only if it is not provided, proceed with the concatenation rules that are already in place to create a display element for a set. (Note that this does not apply for locationSet, subjectSet or dateSet, which operate differently.)
- [x] Document batch ingest (VRA) xml input requirement, xml transformations and validations for the Images application

## SIGNOFF
This was a significant change, we would like full UA/regression testing. 

- [ ] stakeholder sign off (Full UA testing)

-----------------------------------------------
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no (** can be worked around)

### Descriptive summary

Images is not handling valid VRA with sets that contain a display element. It is creating an additional display element in the set. Valid VRA only contains one display element per set.

### Expected behavior

Images should **either** handle valid VRA files which contain sets** with a display element - or reject files which contain them if it will create the display element automatically upon ingest.

**note that some sets excluded: dateSet, subjectSet, locationSet, and titleSet  and appear to be handled differently

For example

```
<vra:descriptionSet>
         <vra:display>Gerhard Mercator ; Scale approximately 1:26,000,000 ; Relief shown pictorially ; "Cum previlegio." ; Verso pages numbered 64 and 61 ; Based on a map from Gerhard Mercator's Atlas sive cosmographicae meditationes de fabrica mundi et fabricati figura ; Map text in Latin. Text on verso in French ; Duisburg: Publisher not identified </vra:display>
         <vra:description>Gerhard Mercator</vra:description>
         <vra:description>Scale approximately 1:26,000,000</vra:description>
         <vra:description>Relief shown pictorially</vra:description>
         <vra:description>"Cum previlegio."</vra:description>
         <vra:description>Verso pages numbered 64 and 61</vra:description>
         <vra:description>Based on a map from Gerhard Mercator's Atlas sive cosmographicae meditationes de fabrica mundi et fabricati figura</vra:description>
         <vra:description>Map text in Latin. Text on verso in French</vra:description>
         <vra:description>Duisburg:</vra:description>
         <vra:description>Publisher not identified</vra:description>
</vra:descriptionSet>
```

### Actual behavior

During batch ingest, in `app/helpers/transform_xml`, Images is concatenating the set elements to create a display element and it is being added to the VRA in addition to any display element already present. 

### Steps to reproduce the behavior

1. Perform a batch ingest including xml with a display element present in a set (like the descriptionSet above)
2. View the resulting VRA created (at the technical metadata endpoint or in Fedora) and observe that the resulting VRA contains two display elements in that set

Example:
```
<vra:descriptionSet>
    <vra:display>
by J. Arrowsmith ; Scale 1:16,500,000 ; Prime meridian: Greenwich ; Boundaries hand-colored ; Relief shown by hachures ; Numbered upper right: "22" ; Detached from : Arrowsmith, J. The London atlas of universal geography. London, 1842-1850 ; London : J. Arrowsmith ; by J. Arrowsmith ; Scale 1:16,500,000 ; Prime meridian: Greenwich ; Boundaries hand-colored ; Relief shown by hachures ; Numbered upper right: "22" ; Detached from : Arrowsmith, J. The London atlas of universal geography. London, 1842-1850 ; London : ; J. Arrowsmith
    </vra:display>
    <vra:display>
by J. Arrowsmith ; Scale 1:16,500,000 ; Prime meridian: Greenwich ; Boundaries hand-colored ; Relief shown by hachures ; Numbered upper right: "22" ; Detached from : Arrowsmith, J. The London atlas of universal geography. London, 1842-1850 ; London : J. Arrowsmith
    </vra:display>
    <vra:description>by J. Arrowsmith</vra:description>
    <vra:description>Scale 1:16,500,000</vra:description>
    <vra:description>Prime meridian: Greenwich</vra:description>
    <vra:description>Boundaries hand-colored</vra:description>
    <vra:description>Relief shown by hachures</vra:description>
    <vra:description>Numbered upper right: "22"</vra:description>
    <vra:description>
Detached from : Arrowsmith, J. The London atlas of universal geography. London, 1842-1850
    </vra:description>
    <vra:description>London :</vra:description>
    <vra:description>J. Arrowsmith</vra:description>
</vra:descriptionSet>
```

### Related work

Related to #349

**Comment by davidschober** [comment]
Talking with @jenyoung. Per original requirements everything except subjectSet and dateSet elements were to concat descriptions. So this may be a non-issue and an errant transform. Retesting.

**Comment by davidschober** [comment]
This is a fairly serious problem. 

The estimate for this work is a week to two weeks with testing.

**Comment by davidschober** [comment]
@kdid and @csyversen I'd like you dig into this deeper after the new year (or before if the other work goes well). I'll put it at the top of ready. After discussing with the team, the risk of bad data seems pretty high.

**Comment by jenyoung** [comment]
If a display attribute is supplied for an element Set, that should be used. Otherwise, a display should be generated upon ingest.

**Comment by kdid** [comment]
@jenyoung, you know you cannot supply display elements on an initial publish from Menu, correct?

**Comment by jenyoung** [comment]
except for date and subjects which we do supply in Menu, otherwise yes

**Comment by davidschober** [comment]
@kdid per our discussion this morning, do you want to close this and create a documentation issue?

**Comment by davidschober** [comment]
@jenyoung can you review and give the OK to merge/close?

**Comment by jenyoung** [comment]
will test with afri maps sample this week.

**Comment by jenyoung** [comment]
tested with a batch of three records - had display elements, no vra:work and made sure it had the relationSet. they all failed. sidekiq error below. i can't see the rest of the error message so i don't know which element is failing.

![2017-02-17_113940](https://cloud.githubusercontent.com/assets/2250501/23076464/386f0cae-f506-11e6-9a8f-a8cbe24b6950.jpg)

**Comment by kdid** [comment]
@jyo - I think this is because you have provided a display for locationSet. locationSet is an exception to the rule handled by different logic than the rest of the sets and will error if you provide the display elements. I've not had a chance to confirm that this is your problem but from a quick glance that's my guess.

Did you get a chance to take  look at the doc I wrote about what XML batch is looking for?

https://github.com/nulib/images/wiki/Batch-Ingest-Input-VRA-XML#additional-xml-requirements

**Comment by davidschober** [comment]
@jyo and I discussed. She will retest without locationSet.

**Comment by csyversen** [comment]
@jenyoung can you please retest this too? thanks!

**Comment by jenyoung** [comment]
tried to batch ingest a vra:image record without a locationSet display. Failing in sidekiq. There should be no vra:work in these records, correct?

"RuntimeError: Had a problem saving /dropbox/batches/jy_test/jen_test_2017_3_3.tif: The resulting VRA Work datastream does not validate. ["Validation error: Element '{http://www.vraweb.org/vracore4.htm}..."

**Comment by kdid** [comment]
@jenyoung - I'm still seeing a display element in the locationSet in /dropbox/batches/jy_test/jen_test_2017_3_3.xml

```
<!--Location-->
      <vra:locationSet>
         <vra:display/>
     ...
      </vra:locationSet>
```

**Comment by jenyoung** [comment]
my bad! it works now!

**Comment by davidschober** [comment]
@jenyoung I was talking to the devs and this issue is fairly complex and changed core logic, we really need to do a full regression test on this. (Run publishing through it's paces --batch, menu, editing, etc). Can you and the testing team schedule time and kick off a formal test, before sign off?

**Comment by jenyoung** [comment]
signing off - push to production when ready

**Comment by davidschober** [comment]
Thanks jen. Make it so team..

**Comment by csyversen** [comment]
cool, i'll talk with the team to see what's up, but hopefully i'll do it tomorrow

**Comment by kdid** [comment]
This is done. Closing

**Comment by davidschober** [comment]
Great work.
