### ISSUE TITLE
Investigate images with missing originals

### ISSUE THREAD

**Issue by davidschober** [nulib/images#354]
### Descriptive summary

This issue relates to #322 

The team will need to locate other copies of and reimport the set of images that do not have original tiffs. (see #322)

**Comment by jenyoung** [comment]
@Nic4Images pids for investigation https://northwestern.app.box.com/notes/101502367807
https://northwestern.app.box.com/notes/101501262573

**Comment by kdid** [comment]
@Nic4Images and @davidschober - these from #326 also don't have .tifs - not sure if you needed to track those as well

https://northwestern.box.com/s/xnqjugfqidcpvuretvfwpxcjtl7x3ox9

**Comment by Nic4Images** [comment]
Hi, I have been reviewing the files and many are from collections cataloged in 2015. The Tiffs should be in Completed on Images Dropbox. I will spot check them on Monday. Update to come!

**Comment by Nic4Images** [comment]
Current collections identified in this list : Alexander Hesler Photograph Collection (Public and cataloged Fall 2016), Study Photographs, Department of Theatre. Linda Roethke. (DIL and cataloged September 2015-June 2016) ..

**Comment by davidschober** [comment]
@Nic4Images and @kdid I thought it might be easier to parse the found/not found dump in a spreadsheet so I put it into columns https://northwestern.app.box.com/files/0/f/16299654001/2017_tifs_missing

I kept the same naming scheme as I can't remember if those files were separated for some reason.

**Comment by Nic4Images** [comment]
@kdid do you remember when we asked Jim to do this? David is here with me and wondering.

**Comment by davidschober** [comment]
@kdid and @csyversen scratch the above comment. Couldn't remember timeline on #346 , etc. Let's discuss whether we can dig try to match some of these using accession on the old _completed.

**Comment by davidschober** [comment]
We did a sampling from these spreadsheets https://northwestern.app.box.com/files/0/f/16299654001/2017_tifs_missing and found that we tested in _completed under jobID/jobID_accession.tif.

**Comment by davidschober** [comment]
Nicole, one last spreadsheet to review. These are ~6k that seem to be old ones (job is voyager).  https://northwestern.app.box.com/files/0/f/16299654001/1/f_121809914553

**Comment by davidschober** [comment]
This was getting unwieldily I moved ^^^ to #357. This issue will be for moving tifs from _completed.

**Comment by davidschober** [comment]
Created #358 to do work.
