### ISSUE TITLE
Delete 6k old images without tiffs

### ISSUE THREAD

**Issue by davidschober** [nulib/images#357]
##DONE
Please remove the PIDs on this spreadsheet per @Nic4Images OK. These images were imported from voyager and have no accompanying tiffs. 

https://northwestern.app.box.com/files/0/f/16299654001/1/f_121809914553

**Comment by Nic4Images** [comment]
@davidschober  I approve of this list of PIDS being deleted from Images. It is the old stuff I have known is lacking Tiffs. Thanks, N.

**Comment by csyversen** [comment]
ok, just to double check on this ( @Nic4Images ) : you want me to delete these 6k records from production Images? 

I can do this tomorrow morning if so!

**Comment by Nic4Images** [comment]
Hi, That is correct. Merci!

**Comment by csyversen** [comment]
(also i have avalon sprint planning tomorrow morning and then an Arch demo so this will probably have to wait until monday)

**Comment by Nic4Images** [comment]
Okay, I will be at the ARLIS-NA conference through Wednesday morning or afternoon thus if I need to be here for this know I am unavailable those days.

**Comment by csyversen** [comment]
I think we should be ok unless you want to check up on it or something! It's your call, I can hold off if you'd like! @Nic4Images

**Comment by Nic4Images** [comment]
I do not see an issue with it. If you want spot checking or such it will just have to wait. Tho I can't think of anything to spot check!

**Comment by csyversen** [comment]
I'm going to hold off on this for about a week because other issues have popped up. This is still on our radar though!

**Comment by csyversen** [comment]
hey @Nic4Images , i'm back to getting ready to run this! is it ok to run this today?

**Comment by Nic4Images** [comment]
Sounds good! I am here if you need me.

**Comment by csyversen** [comment]
This just finished! It looks like all 6308 records were deleted successfully. I spot checked several records and they aren't showing up anymore! @Nic4Images
