### ISSUE TITLE
Move/Copy missing tifs from _completed

### ISSUE THREAD

**Issue by davidschober** [nulib/images#358]
### Descriptive summary

This issue relates to #354 

The team will need to locate other copies of and reimport the set of images that do not have original tiffs. (see #322)

### DONE

note, this was updated after investigative work. 

Please reimport tifs from  [pid_results](https://northwestern.app.box.com/files/0/f/16299654001/1/f_120873855603) and [pid_results2](https://northwestern.box.com/s/0q01erz9cbrisnkkx7ak1vvuahdeshcz). The process should be similar to the mdid import process. The team spot checked against _completed and found all images.

The images are stored in _completed/jobid/jobid_accession.tif and will need to be matched up to PIDs, renamed, and copied. 

### Background
For a full discussion, please see #354

**Comment by davidschober** [comment]
@kdid I spun this off from 354 which became a bit of a bigger investigative story.

**Comment by csyversen** [comment]
@davidschober @kdid ok, so to match up the TIFFs that are in _completed (and named with jobid_accession.tif) , we'll have to search solr i guess for matching accession numbers for each record, right? Is there another way of doing this that i'm not thinking of?

**Comment by davidschober** [comment]
I'll leave this to @kdid. She and Brendan put together something for the MDID thing. Do you have a gist?

**Comment by bmquinn** [comment]
@Nic4Images @jenyoung here's a spreadsheet of the 16 images that had errors during the process of copying @kdid and I ran on Friday: [errors.xlsx](https://github.com/nulib/images/files/838566/errors.xlsx). It looks like several of these are test images based on the accession numbers but not all, so if you could take a look that would be great.

Thanks!

**Comment by kdid** [comment]
The missing tifs have been restored. Closing this issue.
