### ISSUE TITLE
Log Rotation on Images. Keep logs for 60 days.

### ISSUE THREAD

**Issue by kdid** [nulib/images#359]
On images-p, we see 4 days of archived logs. On images-s we see 7 days.

We need to have access to logs for the last 2 months (or 60 days) before they are removed.

**Comment by Toputnal** [comment]
I have set the log rotation for Images 60 days for both production and staging.  Staging has 3.5 GB used under /var and is 88% free.  Production has 34GB used under /var and has 25% disk free.  If we start to get Paged about space issues on Production, we will need to cut this number back.  @kdid @csyversen

**Comment by davidschober** [comment]
@kdid and @csyversen closing this as done.
