### ISSUE TITLE
Restart Staging

### ISSUE THREAD

**Issue by davidschober** [nulib/images#360]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

### Descriptive summary
@Toputnal or @d-venckus can you restart images staging. The box is running out of memory and we're trying to figure out what might be causing the issue. 

@kdid or @csyversen to followup.

**Comment by d-venckus** [comment]
Images-s has been rebooted. Memory usage is low at present, only about 10% of the 16GB configured for it.

**Comment by davidschober** [comment]
Good, I'll close this. @jenyoung and @kdid and @Nic4Images feel free to test and verify.
