### ISSUE TITLE
please wipe image-s Monday 1/30

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#363]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

### Descriptive summary

@csyversen please run the wipeout script on staging on Monday 1/30.

**Comment by csyversen** [comment]
i've been updating slack, but this is in progress right now. Solr has been cleared and fedora is still running

**Comment by csyversen** [comment]
this is mostly done, i just need to recreate the DIL collection. I'll update this ticket once that's done

**Comment by csyversen** [comment]
ok, done!
