### ISSUE TITLE
Slow loading time on images in public collections off campus.

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#364]

**Comment by ccaizzi** [comment]
Both Nicole and I noticed this off campus.  When I was testing this past week, I literally got up to get coffee and came back and still no image had loaded when you are within an image record.  I also am seeing images stall (are fuzzy) even now on campus.

**Comment by davidschober** [comment]
Is it images that are new/ not previously loaded? If images are not cached load time can vary. To solve this would take a different architecture.

**Comment by ccaizzi** [comment]
They were not new.

**Comment by davidschober** [comment]
I shouldn't have said "new". It's really whether an image has been hit before. I hit some images that seem as if they're not cached. After the iiif server caches them, they load fast. I fear what is happening is some users are hitting deeper images, kicking off a bunch of resizes (the RIIIF server resizes on the fly) slowing down the machine as a whole. 

I see two options:
* Try to stand up varnish in front of images to allow faster load times on cached pages and protect the server (devops work)
* scratch the idea of having a multi-zoom image on the initial load of an image, have a zoom button that blows up the image and allows for deep zooming. 
* Both.

We can talk more. Both of these will take some work.

**Comment by davidschober** [comment]
didn't mean to close this. Clicked close other than comment.

**Comment by davidschober** [comment]
Just spoke to CC. We should keep an eye on this, but for now I'll close the issue.

Looking at average load times in the last month individual record urls had load times of ~4seconds. The top 1000 URLs were significantly shorter. Two significant blips pushed load times into the 20s. On listing pages the average load time is 2.67 seconds with one significant blip on Thursday Jan 26.
