### ISSUE TITLE
change links to cataloging procedures and help from MENU

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#366]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

### Descriptive summary

Cataloging guidelines 

New link 
https://share.northwestern.edu/dept/LIB/rdc/Procedures/Cataloging%20Guidelines.aspx

MENU help

new link
https://share.northwestern.edu/dept/LIB/rdc/Procedures/MENU%20help.aspx

**Comment by davidschober** [comment]
@csyversen can you grab  this while you're in there ?

**Comment by jenyoung** [comment]
@csyversen did this happen? just curious. thanks

**Comment by csyversen** [comment]
nope! i'll do it now though.
