### ISSUE TITLE
Images in public collections are slow to load.

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#367]
Trans (5th floor) : In some cases the image “fuzziness” takes over 30 seconds to disappear or part of the menu will be fuzzy while part will be clear. Browser Chrome.
Spec (Deering) : it doesn't seem to be working well. yeah, when you first open tabs of zoomed in images there's nothing there, then eventually they load. Browser: Chrome.
R&DC (2E) : Erin and I noted they are loading fine. Browser/s: Chrome, FireFox

**Comment by davidschober** [comment]
@Nic4Images is this happening consistently on specific images? 

I worked through a series of images -- some fairly deep and saw no problems. I fear this might be our known issue, namely that when under conversion load the entire system gets very slow. I think this is the same issue noted in #364

**Comment by Nic4Images** [comment]
Ugh, I will watch it tomorrow then. If it is the same issue then I will have to tell the curators there is nothing we can do about it right now. Next Gen!

**Comment by kdid** [comment]
I just did a sanity check on the server and everything looks alright. I'm seeing slowness only when converts are going on so I'm inclined to agree with David that this is the same known issue.

**Comment by Nic4Images** [comment]
I will have to say something to curators like Roberto thus I will explain this is just how it functions right now and then spin Next Gen. Thanks, N.

**Comment by davidschober** [comment]
closing this specific issue.
