### ISSUE TITLE
MENU is not publishing new records.

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#368]
MENU is throwing us the null message and refusing to publish new records. Erin has tried all of her tricks and nothing is working. Edit works.

**Comment by davidschober** [comment]
@Nic4Images can you add some sample records (or point us to the ones that won't publish).

@kdid @bmquinn can you look into this? If @carrickr has time it might be a good introduction, but we're trying to release 6.0. 

Also this might be a good "look over a shoulder" for Adam.

**Comment by Nic4Images** [comment]
Ex of ones we tried to publish 11775_320666, 11795_duntley35824, 11795_duntley35825, 11775_320667

**Comment by kdid** [comment]
It looks like on Images getting the JHOVE error again

```
I, [2017-03-01T15:51:33.595478 #49067]  INFO -- : Deleting work and image because Error when running JHOVE against /images_dropbox/11775/11775_320666.tif
```

and has the Java memory error again.

```
[deploy@images-p log]$ java -version
Error occurred during initialization of VM
Could not reserve enough space for object heap
Could not create the Java virtual machine.
```

@d-venckus - can dbvops restart?

**Comment by kdid** [comment]
@Nic4Images  - It looks like you are able to publish successfully now? Everything OK?

**Comment by Nic4Images** [comment]
Yes! Erin and I were able to publish yesterday. Thanks!!

**Comment by csyversen** [comment]
cool, done!
