### ISSUE TITLE
Expand farchive13 share

### ISSUE THREAD

**Issue by bmquinn** [nulib/images#373]
farchive13 is nearly full, and if we can get it expanded to 8.0TB that would probably be enough space going forward.

Here's the current usage:
```
isilon1.ci.northwestern.edu:/ifs/data/Library/repository/farchive13
    6.0T  6.0T   32G 100% /farchive/farchive13
```

**Comment by d-venckus** [comment]
I've submitted a request to Don Hammer at NUIT-PIPS to increase the allowed quota size of /repository/farchive13 to the full 8 TB.

**Comment by d-venckus** [comment]
This has been completed.  Please verify and comment.  Thanks.

**Comment by kdid** [comment]
Yes, we checked. It looks like it has been expanded.

```
isilon1.ci.northwestern.edu:/ifs/data/Library/repository/farchive13
                      8.0T  6.0T  2.1T  75% /farchive/farchive13
```

**Comment by davidschober** [comment]
Thanks Don!
