### ISSUE TITLE
Update Images to no longer make .jp2s

### ISSUE THREAD

**Issue by carrickr** [nulib/images#387]
jp2 function is located [here](https://github.com/nulib/images/blob/249e6894b2353ee27974109bd688a341da72bdfc/app/models/multiresimage.rb#L247)

Adjust the app so it just copies over the tiff over rather than calling this function

**Comment by davidschober** [comment]
I think we should probably resize to 10k by 10k

**Comment by kdid** [comment]
@davidschober and @carrickr - we need to have a discussion about clearing the cache on production. I think we were all assuming existing cache could remain but @bmquinn and I did some testing on staging and images that were partially cached (i.e. someone viewed the page but didn't zoom or pan, or all tiles didn't load, etc) will display funky. See screenshot.

![screen shot 2017-04-27 at 3 07 36 pm](https://cloud.githubusercontent.com/assets/6372022/25502386/fdab3516-2b5b-11e7-8679-b9e03c3a858c.png)

**Comment by davidschober** [comment]
K. Can we time a clear with an automatic rebuild for public (or popular public) ones? I wrote a script when this launched to march through the top 500 images. But I think you two said you just wrote something that went deeper?

**Comment by kdid** [comment]
@davidschober - we just cleared the cache on staging if you want to peek at performance with no cache....
