### ISSUE TITLE
Increase size of images share

### ISSUE THREAD

**Issue by davidschober** [nulib/images#388]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

## Done looks like

To facilitate the conversion of jp2s to access-quality tifs, please add 15tb of storage to  /var/www/html/dimages/ (PRODUCTION)

This is overkill, but we will be running a conversion script on ~100k images and don't want the share to run out space due to temp files, etc.

As discussed during the last PIPs meeting, we should not be gated to an 8tb share, so this is a perfect test. 

### Descriptive summary

We have found the smoking gun in the on-the-fly conversions. ImageMagick  is dealing very inefficiently with jp2s. We have decided to migrate to tiffs allowing us to use RIIIF as intended. The speed increase is an order of magnitude faster. (This has been tested in #384) on production and in staging. Staff has been blocked from doing work.

We would like to do a massive conversion of jp2s to tifs over the weekend.

**Comment by davidschober** [comment]
@carrickr @bmquinn and @kdid this is tracking space increase

**Comment by davidschober** [comment]
From a slack discussion yesterday:

@d-venckus wanted to know if we can expand a different share:

The /dlun1/dimages share on Isilon is currently allocated with 3 TB.  If we increase it to 18 TB, I can't see how we'll return the storage back for use elsewhere.  We'll have this giant share that won't be used after the conversion.

[5:38] 
Is there *any* possible way to use a different path for these conversions?

[5:40] 
 Any reason that the script couldn't use a different work area other than "/var/www/html/dimages/"?

**Comment by davidschober** [comment]
@bmquinn @carrickr @kdid can you check the above... Could we also just expand another share, put the tifs there then symlink to the current location?

**Comment by bmquinn** [comment]
Hi @davidschober and @d-venckus, I think there's maybe a misunderstanding of why we need the expansion of /dlun1/dimages. This expansion is not requested for a temporary conversion, but rather as permanent storage for newly converted TIFFs to be served by the Images application from now on (as opposed to JP2s, which are giving us performance problems with ImageMagick and are much smaller in file size than their TIFF counterparts).

**Comment by davidschober** [comment]
Sorry if my wording was off. Yes, this is a not a temporary fix.

**Comment by Toputnal** [comment]
Ok.  So, @bmquinn there's an expectation that the dimages share, when grown from 3TB to 18TB will consistently be using much closer to 18TB than 3TB because it will be serving TIFFs as opposed to JP2s?

**Comment by Toputnal** [comment]
@d-venckus @bmquinn @davidschober I'll put in a ticket with NUIT to increase the share from 3TB to 18TB and then post the ticket number here.

**Comment by davidschober** [comment]
Thanks @Toputnal

**Comment by Toputnal** [comment]
Opened NUIT Ticket # 527108

**Comment by d-venckus** [comment]
Aaah, looks like my comment/question from last night didn't go through.  I asked whether it was possible to do the conversion work in a different share from dimages, so that we might return the storage back to other uses after the conversion is done.  Is it possible to work in a different share/dir?

**Comment by d-venckus** [comment]
Sorry, I didn't see Brendan's post above.  OK, so not just a temporary conversion.  Now a question:  how much larger is a TIFF file than the equivalent JP2?  I'm trying to get a sense of how much space this share will truly need.  Where did the 18TB figure come from?

**Comment by bmquinn** [comment]
No problem, we're basing the estimate on an assumption of ~90-100MB per TIFF (lots of variance between individual tiff sizes, but capped at 10,000px max in either dimension which would be ~500MB at the high end), and we have 150,000 to convert. So, that's ~14TB for what we have plus some room to grow because there are some large batches in the queue coming up.

**Comment by d-venckus** [comment]
Thanks Brendan.  Yeah, 100MB * 150,000 = 15TB.  So 18TB makes perfect sense.

BTW, how are you going to handle maps, if you're capping the resolution like that.  Won't that limit detail somewhat?

**Comment by d-venckus** [comment]
Don Hammer has increased the quota on /dlun1 (dimages) to 18TB, of which just under 17TB is currently available.  Y'all are good to go with image conversions this weekend.

**Comment by bmquinn** [comment]
Cool! We did a test run of the largest Afri maps using TIFFs instead of JP2s yesterday and determined that the resolution was good enough for viewing the detail (reading small print, seeing paper texture, etc.)

**Comment by bmquinn** [comment]
Just verified this as well. Thanks @Toputnal!
