### ISSUE TITLE
Remove extraneous images from the dimages dir

### ISSUE THREAD

**Issue by carrickr** [nulib/images#389]
Any jp2 that doesn't exist in solr as a multires image does not need to be converted to .tiff.  Find a location to move these rather than convert them.

**Comment by jenyoung** [comment]
please don't forget the missing tiffs that need to be found 
https://github.com/nulib/repodev_planning_and_docs/issues/18

@Nic4Images

**Comment by carrickr** [comment]
@jenyoung For display purposes we'll just use the jp2 display copies to make our display tiffs.  This issue is dealing with improving performance.

**Comment by carrickr** [comment]
We've moved all .jp2s that don't have a solr record to `orphans`.  

@davidschober We need a final call on what to do with the .jp2s

**Comment by davidschober** [comment]
What's our confidence level that these were deleted from images (e.g. there's no associated metadata)?

**Comment by bmquinn** [comment]
Most of the orphans are likely from either deleted image records, batch testing or batch retries in sidekiq ( which used to create many orphaned derivatives during retry cycles but is now fixed)

**Comment by davidschober** [comment]
Thanks. I'll dig into this a bit with the stakeholders. let's get a final size count on data when we're done. It sounds like our orphans were due to the system.

**Comment by Nic4Images** [comment]
If the metadata is not there for these then it sounds okay to get rid of them.

**Comment by jenyoung** [comment]
i agree with Nicole. No metadata, no problem deleting

**Comment by davidschober** [comment]
k. Let's get a count when we're done.

**Comment by carrickr** [comment]
Those without  a record are:

[oprhans.txt](https://github.com/nulib/images/files/968934/oprhans.txt)

Counnt: 38759

**Comment by davidschober** [comment]
Cool. Let’s hold these for now.
