### ISSUE TITLE
Convert Remaining Public Collections from jp2 to tiff

### ISSUE THREAD

**Issue by carrickr** [nulib/images#393]
## Collections:

- [x] Rob Linrothe Image Collection 5,028
- [x] Vernon McKay Photographs 1,777
- [x] Jim Roberts Photographs, 1968-1972 1,663
- [x] Justine Cordwell Collection 1,460
- [x] Alexander Hesler Photograph Collection 948
- [x] University Archives Postcards 796
- [x] Ira Silverman Railroad Menu Collection 790
- [x] Posters from the Herskovits Library 594
- [x] United States Army Base Hospital Number 12 World War I and II Records 558
- [x] World War II Poster Collection at Northwestern University Library 405
- [x] George Silas Duntley (1879-1957) Photographs, circa 1899-1918 398
- [x] Hamid Naficy Iranian Movie Posters Collection 251
- [x] Kate and Lou. Souvenir of auto trip to San Francisco, 1915 232
- [x] The Siege and Commune of Paris, 1870-1871 122
- [x] Ramón Casas sketchbooks 108
- [x] Department of Art History, Study Photographs Collection 89
- [x] WPA Digital Collection, 1935-1943 50
- [x] Ifeoma Onyefulu : photographs 41
- [x] Une cité moderne : dessins, by Rob Mallet-Stevens 23
- [x] Photographs of Zanzibar 16
- [x] Album 15
- [x] Depictions of Africa in French humour magazines 14
- [x] Wilmo Engines #392

**Comment by carrickr** [comment]
@jenyoung I was just going to go down this list, any collections that are currently problematic and you would like converted first?  La Caricature and Africa Maps are already done

**Comment by jenyoung** [comment]
@carrickr we are currently cataloging and adding  to Jim Roberts & Army Base Hospital public collections. Perhaps do those first?  After that I think the three poster collections (WWII, Africa, and Naficy).

**Comment by davidschober** [comment]
Jen, can you give the URL just for verification. If you're cataloging and adding to it, we would need the images being cataloged as well as the images that are currently in the public collection.

**Comment by carrickr** [comment]
@davidschober As long as they are part of the collection facet, my script will get them.  If @jenyoung has them stashed elsewhere, then I'd need that as well.

I just started the script for everything under the `Jim Roberts Photographs, 1968-1972` facet.  Not sure how long it will take as the images are much smaller than some of our other collections, but we have many more.

**Comment by jenyoung** [comment]
@carrickr  just talked to @davidschober - go ahead and plow through the public collections.  the ones we add to collection later will be scooped up later on.

**Comment by carrickr** [comment]
@jenyoung Roberts is done, looks like 1,707 converted.  Moving on to WWII

**Comment by carrickr** [comment]
All public collections are done, ready for QA.

**Comment by ccaizzi** [comment]
This is SO much better (I am not doing QA) but this really did help our end user experience in the few I have clicked around into.  Thanks, team!!

**Comment by davidschober** [comment]
Thank you all so much. This looks great. @Nic4Images and @jenyoung can you spot check and give final sign off/ close the issue

**Comment by davidschober** [comment]
Spot checked. Closing.
