### ISSUE TITLE
Convert DIL on Images from jp2 to tiff

### ISSUE THREAD

**Issue by carrickr** [nulib/images#395]
Convert Digital Image Library (104,098 images) from jp2 to tiff.

**Comment by carrickr** [comment]
@davidschober Just ton confirm, we are cleared to move on the private ones as well?

**Comment by davidschober** [comment]
Yes. Do we have an estimate on size after doing the last few converts? (you don't have to kick this off while you're gone).

**Comment by carrickr** [comment]
Not as much as we thought, we're only using 18% of dimages after converting all the public collections (which had the larger images).
