### ISSUE TITLE
titles with "Untitled"

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#403]
Many of the objects with a title of "Untitled" actually have titles. Start cleanup with the Public Collections first please. Keyword search "Untitled"

This affects Primo.

- [ ] Digital Image Library **1,683**
- [x] Justine Cordwell Collection **434**
- [x] Ramón Casas sketchbooks **107**
- [x] La Caricature (1830-1835; Charles Philipon, founding editor) **3**
- [x] Kate and Lou. Souvenir of auto trip to San Francisco, 1915 **2**

**Comment by egilchrist** [comment]
Public collections clean-up in complete.  Created a new issue just for "Untitled" in DIL.  Closing this issue for public collections.
