### ISSUE TITLE
Deal with remaining JP2s in prod derivative directory

### ISSUE THREAD

**Issue by bmquinn** [nulib/images#410]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [x] no

There are 39291 JP2's in derivatives directory that we should probably deal with. We should probably run the batch conversion script to catch the images ingested since the last run, and delete those that remain.

**Comment by davidschober** [comment]
@mbklein can you let me know if this is done?
