### ISSUE TITLE
"Unknown" as title

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#413]
"unknown" as title group 
http://images.northwestern.edu/dil_collections/inu:dil-local-91bc6d24-4da2-4109-b8c8-c4d9d47591bb

**Comment by davidschober** [comment]
@jenyoung this has been sitting in this column for a bit. is it still being actively worked on? If not, let's move it to done/ ready.

**Comment by jenyoung** [comment]
@davidschober yes it is still being worked on.

**Comment by davidschober** [comment]
OK. I wonder if we should break up issues like this. It’s been in in progress for quite a while.

**Comment by jenyoung** [comment]
Images doesn't parse things like we want so it takes time. There really isn't much of a way to break it up. Also, removing items from a group doesn't seem to work anymore. This is a low priority for Erin, but it is her work.

**Comment by jenyoung** [comment]
Erin was working on this. I'm ok with closing.
