### ISSUE TITLE
Newly ingested images are not loading properly into Images. 

### ISSUE THREAD

**Issue by Nic4Images** [nulib/images#414]
###

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

Our temp Jen just informed me newly cataloged images are not loading properly into Images. All we see is a line where the image should be. (See screenshot.)

### Steps to reproduce the behavior

1. Do this search for 11813 in Images
1. Then do this... click on random images until the line starts appearing. The first few display images.

### Related work

Link to related tickets or prior related work here.

**Comment by Nic4Images** [comment]
<img width="1301" alt="screen shot 2017-06-30 at 4 16 04 pm" src="https://user-images.githubusercontent.com/20801226/27754645-fbe2c104-5db0-11e7-9ae2-6a47303d2729.png">

**Comment by Nic4Images** [comment]
<img width="1301" alt="screen shot 2017-06-30 at 4 29 10 pm" src="https://user-images.githubusercontent.com/20801226/27754696-4f5684a6-5db1-11e7-9112-0583794c2dae.png">

**Comment by davidschober** [comment]
I think you meant to leave this open correct?

**Comment by kdid** [comment]
These tiffs have multiple layers. (Example or running Imagemagick's identify command on one image):

```
$ identify inu-dil-a7bdccb5-d856-4c73-a993-d50b6845bbcf.tiff
inu-dil-a7bdccb5-d856-4c73-a993-d50b6845bbcf.tiff[0] TIFF 9599x6889 9599x6889+0+0 8-bit sRGB 198.4MB 0.010u 0:00.009
inu-dil-a7bdccb5-d856-4c73-a993-d50b6845bbcf.tiff[1] TIFF 160x115 160x115+0+0 8-bit sRGB 198.4MB 0.000u 0:00.009
```

```
$ identify -format %hx%w inu-dil-a7bdccb5-d856-4c73-a993-d50b6845bbcf.tiff
6889x9599115x160
```

The riiif gem seems to be assuming one layer so when it calculates the width and height it is ending up with the wrong value (in this example, it ends up with: 6889x9599115). This incorrect value is throwing off the calculations in the riiif requests to load the image tiles in the viewer and causing the display problems. 

So, @Nic4Images is there a reason why riiif should be handling tiff's with multiple layers? Or should our images not have these multiple layers?

**Comment by davidschober** [comment]
@dzellner can you shine any light on this?

**Comment by dzellner** [comment]
That's strange - I will have to take a look at these images. These came from one of our vendors

**Comment by dzellner** [comment]
@kdid can you generate a list of the tiffs that have multiple layers? We can then fix them and also figure out the source of the problem (vendor or part of our QC process.  Thanks,  Dan

**Comment by bmquinn** [comment]
@dzellner I'm running a script on the images now, but it might take a long time to run since there are so many of them (100,000+). Will get you the list of images as soon as the script is finished.

**Comment by dzellner** [comment]
Thanks Brendan!

**Comment by bmquinn** [comment]
@dzellner I dug a little deeper into the problem and it looks like it is upstream in the `riiif` gem. So, I cancelled the script since it was going to take days anyways. We're getting:

```ruby
Riiif::CommandRunner.execute("identify -format %hx%w #{path}").split('x')
Riiif executed identify -format %hx%w test.tif (14.7ms)
=> ["6858", "9653114", "160"]
```
The "9653114" value being the problem. We want to be getting:

```ruby
=> ["6858", "9653"]
```

Working on a bugfix to submit to `riiif` now. Looks like the problem comes from [this line](https://github.com/curationexperts/riiif/blob/master/app/services/riiif/image_magick_info_extractor.rb#L9) for the curious)

**Comment by davidschober** [comment]
@bmquinn Thanks! @Nic4Images FYI.

**Comment by bmquinn** [comment]
`riiif` pull request merged yesterday: https://github.com/curationexperts/riiif/pull/80

I'll update the `riiif` gem when a new release is cut for riiif and we should be good to go. Does that sound good to folks?

**Comment by davidschober** [comment]
Sounds great!

**Comment by dzellner** [comment]
Thanks for your work Brendan!

**Comment by davidschober** [comment]
Note, we are waiting for a final release of riiif on this.

**Comment by dzellner** [comment]
Any idea when final release will be happening?  Jenn (cataloger) has only a little more time on this project and she's trying to wrap up all the cataloging.

**Comment by davidschober** [comment]
Team do you think we can nudge Justin to tag it?

**Comment by jenyoung** [comment]
@dzellner is going to look at the current jobs for Jenn to see if they have the layer issue. If they do, then it's a work stoppage for her which is not good.

**Comment by davidschober** [comment]
we're working on getting a tagged release from upstream. This was a pretty serious bug.

**Comment by davidschober** [comment]
@bmquinn @kdid @csyversen did @mbklein close this accidentally?

**Comment by bmquinn** [comment]
![correct_dimensions](https://user-images.githubusercontent.com/1395707/28725619-a7166cfa-7383-11e7-9492-ea876473e885.png)

Deployed and tested on production.
