### ISSUE TITLE
Install GraphicsMagick on Images-s and Images-p

### ISSUE THREAD

**Issue by davidschober** [nulib/images#416]
## Description

The new RIIIF server is configurable to use GM instead of IM. GM  **should** offer faster response with fewer resources. We would like to test this on staging and production.

## Done looks like

- [x] graphicsmagick is installed on staging
- [ ] graphicsmagick is installed on production
- [x] documentation and puppet is updated as necessary

## NOTE

GM can live side-by-side with IM, please leave both. 

## Reference

<http://www.graphicsmagick.org>

**Comment by Toputnal** [comment]
The latest version of GraphicsMagick and GraphicsMagick-devel are installed on images-s via puppet.  Feel free to run whatever tests are needed before we do the same for production.  @davidschober

**Comment by davidschober** [comment]
@kdid @bmquinn @csyversen

**Comment by davidschober** [comment]
@bmquinn @csyversen @kdid it's there if you want to mess with it.

**Comment by egspoony** [comment]
This is abandoned.
