### ISSUE TITLE
Naficy collection name in records

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#417]
Change "Hamid Naficy Iranian Movies Poster Collection" to "Hamid Naficy Iranian Movie Posters Collection"

**Comment by jenyoung** [comment]
look in the element '<vra:location type="repository">
<vra:name type="other">Hamid Naficy Iranian Movies Poster Collection</vra:name>
</vra:location>'

**Comment by egilchrist** [comment]
Completed editing Naficy collection name. Searching for "Hamid Naficy Iranian Movies Poster Collection" in Images no longer has any results.  Going to close the issue but feel free to double-check me.
