### ISSUE TITLE
Two posters incorrectly in Naficy

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#418]
these two posters about Assata Shakur were added as part of the Naficy Collection. They are from Herskovits.

http://images.northwestern.edu/multiresimages/inu:dil-3533d9de-1ea7-4a6a-9aef-f7da9769d489

http://images.northwestern.edu/multiresimages/inu:dil-83bfb666-cf1c-4066-92d7-082bcb410866

**Comment by jenyoung** [comment]
@Nic4Images were these supposed to be part of the Naficy collection?

**Comment by jenyoung** [comment]
@Nic4Images can you comment please?

**Comment by Nic4Images** [comment]
They are removed! Sorry for the delay.
