### ISSUE TITLE
Renew SSL certs for images-p, images-s, images-d.

### ISSUE THREAD

**Issue by d-venckus** [nulib/images#429]
SSL cert for images-p expires on 28 Jan 2018.
SSL cert for images-s expires on 13 Jan 2018.
SSL cert for images-d expires on 13 Jan 2018.

New 3-year certs for each should be issued.  Images-p will require a SAN multi-server cert.

**Comment by d-venckus** [comment]
Generating cert renewals for Images-d/s/p.  Will install later today, which requires updating puppet code for these servers.

**Comment by egspoony** [comment]
The new images-p certificate needs to be regenerated, but the old cert is still in place.
