### ISSUE TITLE
can't get to original tif-- external request

### ISSUE THREAD

**Issue by davidschober** [nulib/images#430]
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

When clicking on the get original tif link from inu:dil-fb0524ef-69e8-42b2-b967-4c15eb7f306b, the app errors with 
<img width="1346" alt="screen shot 2018-01-22 at 2 09 27 pm" src="https://user-images.githubusercontent.com/4803230/35345182-96e59ad2-00f4-11e8-805c-111d4c2dde82.png">

Other images from the same collection are available. 

### Expected behavior
The original tif should download. 

### Steps to reproduce the behavior

1. sign into images
2. Go to https://images.library.northwestern.edu/multiresimages/inu:dil-fb0524ef-69e8-42b2-b967-4c15eb7f306b
3. click "Download original tif
4. see error "Problem retrieving Tif file. 

### Related work

Link to related tickets or prior related work here.

**Comment by csyversen** [comment]
so we store our archival images on our fedora repository at /farchive/farchive13/inu-dil/hydra/ in one of those subfolders based on the environment. While other tiffs from that same collection are in that location, this particular record isnt' in any of them. 

Also the filestream location for that record is odd. It's listed as: 
```
Datastream Location: | http://rstorage.library.northwestern.edu/archive/farchive13/inu-dil/hydra/test/inu-dil-fb0524ef-69e8-42b2-b967-4c15eb7f306b.tif
```
but that /test/ shouldn't be in that url and other records from that same collection don't have that /test/ either. Is this record a duplicate? Or maybe a test record that we accidentally ran in production or something?

**Comment by kdid** [comment]
I see that pid on one of the lists of missing tif's and it doesn't look like it's on one of the lists of pids that Jim found.

https://github.com/nulib/images/issues/322

**Comment by jenyoung** [comment]
if it helps, this image is from that batch of cursed images, aka La Caricature. The jobs that kept not being ingested right during the summer in 2016.

**Comment by csyversen** [comment]
@davidschober I think we need a PO call on what to do next

**Comment by adamjarling** [comment]
Can't do anything else.  Closing
