### ISSUE TITLE
Images not returning images (possibly iiif server)

### ISSUE THREAD

**Issue by davidschober** [nulib/images#431]
## Description

Images are not loading in viewer on images.northwestern.edu

It seems as if the image service itself is having issues. For instance loading a cached thumbnail :

- http://images.northwestern.edu/image-service/inu-dil-a72f3b52-d555-4633-811e-a631456471f5/full/,120/0/default.jpg  works fine

But trying to retrieve a sized image (I'm assuming uncached) or a page of deeper thumbnails throws errors :

- http://images.northwestern.edu/image-service/inu-dil-a72f3b52-d555-4633-811e-a631456471f5/full/,440/0/default.jpg

- http://images.northwestern.edu/catalog?page=9&q=Job%3A11719

**Comment by Toputnal** [comment]
I am not sure if or how this is related, but this is the first sort of warning sign I've seen in all the logs I've checked.  `  Backtrace: /var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/blacklight-5.16.3/lib/blacklight/solr/repository.rb:44:in `block in send_and_receive'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/deploy/.rbenv/versions/2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/benchmarkable.rb:41:in `benchmark'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/blacklight-5.16.3/lib/blacklight/solr/repository.rb:42:in `send_and_receive'
/var/www/dil_hydra/shared/bundle/ruby/2.3.0/gems/blacklight-5.16.3/lib/blacklight/solr/repository.rb:28:in `search'
I, [2018-03-19T12:30:41.947345 #9454]  INFO -- : method=GET path=/catalog format=*/* controller=CatalogController action=index status=302 duration=37.57 view=0.00 db=0.99 location=http://images.northwestern.edu/ params={"f"=>{"date_display_facet"=>["1970"], "subject_term_facet"=>["England"]}, "per_page"=>"10", "sort"=>"agent_dil+asc,+title_dil+asc"}
I, [2018-03-19T12:30:42.540892 #9454]  INFO -- : method=GET path=/catalog format=*/* controller=CatalogController action=index status=200 duration=95.70 view=32.21 db=1.40 params={"f"=>{"date_display_facet"=>["1680"]}, "per_page"=>"20", "q"=>"Guinea"}
I, [2018-03-19T12:30:43.711660 #9454]  INFO -- : method=GET path=/catalog format=*/* controller=CatalogController action=index status=200 duration=61.86 view=9.94 db=1.02 params={"f"=>{"date_display_facet"=>["Circa+15th-16th+century"], "stylePeriod_facet"=>["Tibetan."]}}
  `

**Comment by carrickr** [comment]
Riiif gem seemed to be creating bad images for display.  A redeploy of the code by @csyversen resolved the issue.  @Toputnal removed all files in the rails cache that had been created over the past five days (using today's date 19 March 2018), after which the impacted images loaded properly.  

We want to attempt to avoid a total clearing of the rails cache, since then the script to cache popular images would need to be run and that brings down the server for a period.  If future problems along this line are found, we might need to run a second pass targeting items within 10, 15 or perhaps more days of 19 March 2018.
