### ISSUE TITLE
redirect to sign in is confusing if you're trying to see another user's group

### ISSUE THREAD

**Issue by jenlindner** [nulib/images#64]
you get redirected to sign in, and if you sign in it tells you you're already signed in.

this is happening because the redirect is at the top level of the application controller, rescuing every type of authorization problem and taking denied users to sign in. we need more specific ones, definitely one for groups - if you try to see another user's group, you should not be redirected to sign in, you need to be told you don't have access to that page without being taken to it.

**Comment by csyversen** [comment]
we did it!
